@startuml séquence client
actor client as c
participant système as s
autonumber
c -> s : connexion 
s -> s : vérifie l'adresse mail et le mdp
alt adresse mail introuvable 
autonumber 
s --> c : erreur adresse mail introuvable 
c -> s : création du compte 
s --> c : affiche la page de création de compte
c -> s : saisie de l'adresse mail et du mdp
s -> s : vérifie l'adresse mail et le mdp
c -> s : saisie des données personnelles 
s -> s : vérifie les données du formulaire 
s --> c : valide la création du compte 
alt mot de passe incorrect
autonumber
s --> c : erreur mot de passe incorrect
c -> s : mot de passe oublié
s --> c : affiche la page de vérification de l'adresse mail
c -> s : saisie de l'adresse mail 
s -> s : vérifie l'adresse mail
s --> c : adresse mail validé 
s --> c : envoie du mail de récupération du mdp
c -> s : lien changement de mdp
s --> c : affiche la page de modification du mdp
s -> s : vérifie le mdp
s --> c : confirme la modification du mdp
s --> c : affiche la page de connexion
c -> s : connexion 
s -> s : vérifie l'adresse mail et le mdp
end
end
autonumber 3
s --> c : connexion validé
c -> s : consulte les produits
s --> c : affiche les produits 
c -> s : ajoute des produits au panier 
s -> s : contrôle les stocks
s --> c : confirme l'ajout des produits au panier
c -> s : consulte son panier 
s --> c : affiche le panier 
c -> s : confirme le panier
s --> c : affiche la page de commande
c -> s : choisie le mode de paiement 
s -> s : vérifie le mode de paiement 
alt mode de paiement non valide 
autonumber
s --> c : erreur mode de paiement invalide
c -> s : changement du mode de paiement 
s -> s : vérifie le mode de paiement 
end
autonumber 15
s --> c : valide le mode de paiement 
c -> s : choisie une adresse de livraison / facturation 
alt adresse de facturation non renseigné 
autonumber
s --> c : adresse de facturation non renseigné
c -> s : choisie l'adresse de livraison\ncomme adresse de facturation
else
autonumber 2
c -> s : saisie d'une adresse de facturation 
end
autonumber 17
s -> s : vérifie les adresses 
s --> c : valide les adresses 
c -> s : valide la commande 
s -> s : enregistrement de la commande 
s --> c : commande validé
@enduml

