@startuml séquence client
actor client as c
participant système as s
autonumber
c -> s : connexion 
s -> s : vérifie les identifiants 
alt identifiant introuvable 
s --> c : erreur identifiants introuvable 
c -> s : création du compte 
s -> s : vérifie les identifiants
c -> s : saisie des données personnelles 
s -> s : vérifie les données du formulaire 
s --> c : valide la création du compte 
end
c -> s : consulte les produits
s --> c : affiche les produits 
c -> s : ajoute des produits au panier 
s -> s : contrôle les stocks
s --> c : confirme l'ajout des produits au panier
c -> s : consulte son panier 
s --> c : affiche le panier 
c -> s : confirme le panier
s --> c : affiche la page de commande
c -> s : choisie le mode de paiement 
s -> s : vérifie le mode de paiement 
alt mode de paiement non valide 
s --> c : erreur mode de paiement invalide
c -> s : changement de mode de paiement 
s -> s : vérifie le mode de paiement 
s --> c : valide le mode de paiement
end
s --> c : valide le mode de paiement 
c -> s : choisie une adresse de livraison / facturation 
s -> s : vérifie les adresses 
s --> c : valide les adresses 
c -> s : valide la commande 
s -> s : enregistrement de la commande 

newpage Flot alternatif 
autonumber
c -> s : connexion
s -> s : vérifie les identifiants 
s --> c : erreur identifiants introuvable 
c -> s : création du compte 
s -> s : vérifie les identifiants
c -> s : saisie des données personnelles 
s -> s : vérifie les données du formulaire 
s --> c : erreur donnée erronée 
c -> s : correction
s -> s : vérifie les données du formulaire 
c -> s : valide la création de compte 
s -> s : enregistrement du compte

@enduml

