<?php
/* `filmo`.`personne` */
$personne = array(
  array('id' => '1','prenom' => 'Hayao','nom' => 'Miyazaki'),
  array('id' => '2','prenom' => 'Toshio','nom' => 'Suzuki'),
  array('id' => '3','prenom' => 'Yōji','nom' => 'Matsuda'),
  array('id' => '4','prenom' => 'Yuriko','nom' => 'Ishida'),
  array('id' => '5','prenom' => 'Akihiro','nom' => 'Miwa'),
  array('id' => '6','prenom' => 'Yūko','nom' => 'Tanaka'),
  array('id' => '7','prenom' => 'Tsunehiko','nom' => 'Kamijō'),
  array('id' => '8','prenom' => 'Kaoru','nom' => 'Kobayashi'),
  array('id' => '9','prenom' => 'Sumi','nom' => 'Shimamoto'),
  array('id' => '10','prenom' => 'Hisaya','nom' => 'Morishige'),
  array('id' => '11','prenom' => 'Masahiko','nom' => 'Nishimura'),
  array('id' => '12','prenom' => 'Mitsuko','nom' => 'Mori'),
  array('id' => '13','prenom' => 'Rumi','nom' => 'Hiiragi'),
  array('id' => '14','prenom' => 'Miyu','nom' => 'Irino'),
  array('id' => '15','prenom' => 'Mari','nom' => 'Natsuki'),
  array('id' => '16','prenom' => 'Bunta','nom' => 'Sugawara'),
  array('id' => '17','prenom' => 'Yasuko','nom' => 'Sawaguchi'),
  array('id' => '18','prenom' => 'Takashi','nom' => 'Naitō'),
  array('id' => '19','prenom' => 'Yumi','nom' => 'Tamai'),
  array('id' => '20','prenom' => 'Ryūnosuke','nom' => 'Kamiki'),
  array('id' => '21','prenom' => 'Chieko','nom' => 'Baishō'),
  array('id' => '22','prenom' => 'Takuya','nom' => 'Kimura'),
  array('id' => '23','prenom' => 'Tatsuya','nom' => 'Gashuin'),
  array('id' => '24','prenom' => 'Yō','nom' => 'Ōizumi'),
  array('id' => '25','prenom' => 'Daijirō','nom' => 'Harada'),
  array('id' => '26','prenom' => 'Haruko','nom' => 'Katō'),
  array('id' => '27','prenom' => 'Yayoi','nom' => 'Kazuki'),
  array('id' => '28','prenom' => 'Isao','nom' => 'Takahata'),
  array('id' => '29','prenom' => 'Tōru','nom' => 'Hara'),
  array('id' => '30','prenom' => 'Yoshiko','nom' => 'Shinohara'),
  array('id' => '31','prenom' => 'Ayano','nom' => 'Shiraishi'),
  array('id' => '32','prenom' => 'Tsutomu','nom' => 'Tatsumi'),
  array('id' => '33','prenom' => 'Akemi','nom' => 'Yamaguchi'),
  array('id' => '34','prenom' => 'David','nom' => 'Fincher'),
  array('id' => '35','prenom' => 'Andrew Kevin','nom' => 'Walker'),
  array('id' => '36','prenom' => 'Phyllis','nom' => 'Carlyle'),
  array('id' => '37','prenom' => 'Brad','nom' => 'Pitt'),
  array('id' => '38','prenom' => 'Morgan','nom' => 'Freeman'),
  array('id' => '39','prenom' => 'Gwyneth','nom' => 'Paltrow'),
  array('id' => '40','prenom' => 'Kevin','nom' => 'Spacey'),
  array('id' => '41','prenom' => 'Jim','nom' => 'Uhls'),
  array('id' => '42','prenom' => 'Ross Grayson','nom' => 'Bell'),
  array('id' => '43','prenom' => 'Edward','nom' => 'Norton'),
  array('id' => '44','prenom' => 'Helena','nom' => 'Bonham Carter'),
  array('id' => '45','prenom' => 'Darren','nom' => 'Aronofsky'),
  array('id' => '46','prenom' => 'Hubert','nom' => 'Selby Jr.'),
  array('id' => '47','prenom' => 'Eric','nom' => 'Watson'),
  array('id' => '48','prenom' => 'Jared','nom' => 'Leto'),
  array('id' => '49','prenom' => 'Jennifer','nom' => 'Connelly'),
  array('id' => '50','prenom' => 'Marlon','nom' => 'Wayans'),
  array('id' => '51','prenom' => 'Ellen','nom' => 'Burstyn'),
  array('id' => '52','prenom' => 'Martin','nom' => 'Scorsese'),
  array('id' => '53','prenom' => 'Laeta','nom' => 'Kalogridis'),
  array('id' => '54','prenom' => 'Mike','nom' => 'Medavoy'),
  array('id' => '55','prenom' => 'Leonardo','nom' => 'DiCaprio'),
  array('id' => '56','prenom' => 'Mark','nom' => 'Ruffalo'),
  array('id' => '57','prenom' => 'Ben','nom' => 'Kingsley'),
  array('id' => '58','prenom' => 'Paul','nom' => 'Schrader'),
  array('id' => '59','prenom' => 'Michael','nom' => 'Phillips'),
  array('id' => '60','prenom' => 'Julia','nom' => 'Phillips'),
  array('id' => '61','prenom' => 'Robert','nom' => 'De Niro'),
  array('id' => '62','prenom' => 'Cybill','nom' => 'Shepherd'),
  array('id' => '63','prenom' => 'Peter','nom' => 'Boyle'),
  array('id' => '64','prenom' => 'Jodie','nom' => 'Foster'),
  array('id' => '65','prenom' => 'Katsuhiro','nom' => 'Ōtomo'),
  array('id' => '66','prenom' => 'Izō','nom' => 'Hashimoto'),
  array('id' => '67','prenom' => 'Ryôhei','nom' => 'Suzuki'),
  array('id' => '68','prenom' => 'Mitsuo','nom' => 'Iwata'),
  array('id' => '69','prenom' => 'Nozomu','nom' => 'Sasaki'),
  array('id' => '70','prenom' => 'Mami','nom' => 'Koyama'),
  array('id' => '71','prenom' => 'Tarō','nom' => 'Ishida'),
  array('id' => '72','prenom' => 'Christopher','nom' => 'Nolan'),
  array('id' => '73','prenom' => 'Jonathan','nom' => 'Nolan'),
  array('id' => '74','prenom' => 'Lynda','nom' => 'Obst'),
  array('id' => '75','prenom' => 'Emma','nom' => 'Thomas'),
  array('id' => '76','prenom' => 'Matthew','nom' => 'McConaughey'),
  array('id' => '77','prenom' => 'Anne','nom' => 'Hathaway'),
  array('id' => '78','prenom' => 'Michael','nom' => 'Caine'),
  array('id' => '79','prenom' => 'Jessica','nom' => 'Chastain'),
  array('id' => '80','prenom' => 'Casey','nom' => 'Affleck'),
  array('id' => '81','prenom' => 'Matt','nom' => 'Damon'),
  array('id' => '82','prenom' => 'Charles','nom' => 'Roven'),
  array('id' => '83','prenom' => 'Christian','nom' => 'Bale'),
  array('id' => '84','prenom' => 'Aaron','nom' => 'Eckhart'),
  array('id' => '85','prenom' => 'Heath','nom' => 'Ledger'),
  array('id' => '86','prenom' => 'Gary','nom' => 'Oldman'),
  array('id' => '87','prenom' => 'Maggie','nom' => 'Gyllenhaal'),
  array('id' => '88','prenom' => 'Morgan','nom' => 'Freeman'),
  array('id' => '89','prenom' => 'Cillian','nom' => 'Murphy'),
  array('id' => '90','prenom' => 'Andrew','nom' => 'Adamson'),
  array('id' => '91','prenom' => 'Vicky','nom' => 'Jenson'),
  array('id' => '92','prenom' => 'Ted','nom' => 'Elliott'),
  array('id' => '93','prenom' => 'Jeffrey','nom' => 'Katzenberg'),
  array('id' => '94','prenom' => 'Mike','nom' => 'Myers'),
  array('id' => '95','prenom' => 'Eddie','nom' => 'Murphy'),
  array('id' => '96','prenom' => 'Cameron','nom' => 'Diaz'),
  array('id' => '97','prenom' => 'John','nom' => 'Lithgow'),
  array('id' => '98','prenom' => 'Quentin','nom' => 'Tarantino'),
  array('id' => '99','prenom' => 'Lawrence','nom' => 'Bender'),
  array('id' => '100','prenom' => 'Mélanie','nom' => 'Laurent'),
  array('id' => '101','prenom' => 'Christoph','nom' => 'Waltz'),
  array('id' => '102','prenom' => 'Eli','nom' => 'Roth'),
  array('id' => '103','prenom' => 'Michael','nom' => 'Fassbender'),
  array('id' => '104','prenom' => 'Diane','nom' => 'Kruger'),
  array('id' => '105','prenom' => 'Reginald','nom' => 'Hudlin'),
  array('id' => '106','prenom' => 'Jamie','nom' => 'Foxx'),
  array('id' => '107','prenom' => 'Kerry','nom' => 'Washington'),
  array('id' => '108','prenom' => 'Samuel','nom' => 'L. Jackson'),
  array('id' => '109','prenom' => 'David','nom' => 'Heyman'),
  array('id' => '110','prenom' => 'Shannon','nom' => 'McIntosh'),
  array('id' => '111','prenom' => 'Margot','nom' => 'Robbie'),
  array('id' => '112','prenom' => 'Margaret','nom' => 'Qualley'),
  array('id' => '113','prenom' => 'Al','nom' => 'Pacino'),
  array('id' => '114','prenom' => 'Michael','nom' => 'Mann'),
  array('id' => '115','prenom' => 'Stuart','nom' => 'Beattie'),
  array('id' => '116','prenom' => 'Julie','nom' => 'Richardson'),
  array('id' => '117','prenom' => 'Tom','nom' => 'Cruise'),
  array('id' => '118','prenom' => 'Jada','nom' => 'Pinkett Smith'),
  array('id' => '119','prenom' => 'Ann','nom' => 'Biderman'),
  array('id' => '120','prenom' => 'Ronan','nom' => 'Bennett'),
  array('id' => '121','prenom' => 'G.','nom' => 'Mac Brown'),
  array('id' => '122','prenom' => 'Johnny','nom' => 'Depp'),
  array('id' => '123','prenom' => 'Marion','nom' => 'Cotillard'),
  array('id' => '124','prenom' => 'M.','nom' => 'Night Shyamalan'),
  array('id' => '125','prenom' => 'Frank','nom' => 'Marshall'),
  array('id' => '126','prenom' => 'Sam','nom' => 'Mercer'),
  array('id' => '127','prenom' => 'Mel','nom' => 'Gibson'),
  array('id' => '128','prenom' => 'Joaquin','nom' => 'Phoenix'),
  array('id' => '129','prenom' => 'Rory','nom' => 'Culkin'),
  array('id' => '130','prenom' => 'Abigail','nom' => 'Breslin'),
  array('id' => '131','prenom' => 'Cherry','nom' => 'Jones'),
  array('id' => '132','prenom' => 'Kathleen','nom' => 'Kennedy'),
  array('id' => '133','prenom' => 'Barry','nom' => 'Mendel'),
  array('id' => '134','prenom' => 'Bruce','nom' => 'Willis'),
  array('id' => '135','prenom' => 'Haley','nom' => 'Joel Osment'),
  array('id' => '136','prenom' => 'Olivia','nom' => 'Williams'),
  array('id' => '137','prenom' => 'Toni','nom' => 'Collette'),
  array('id' => '138','prenom' => 'Ridley','nom' => 'Scott'),
  array('id' => '139','prenom' => 'David','nom' => 'Franzoni'),
  array('id' => '140','prenom' => 'John','nom' => 'Logan'),
  array('id' => '141','prenom' => 'William','nom' => 'Nicholson'),
  array('id' => '142','prenom' => 'Douglas','nom' => 'Wick'),
  array('id' => '143','prenom' => 'Branko','nom' => 'Lustig'),
  array('id' => '144','prenom' => 'Russell','nom' => 'Crowe'),
  array('id' => '145','prenom' => 'Connie','nom' => 'Nielsen'),
  array('id' => '146','prenom' => 'Oliver','nom' => 'Reed'),
  array('id' => '147','prenom' => 'Djimon','nom' => 'Hounsou'),
  array('id' => '148','prenom' => 'Richard','nom' => 'Harris'),
  array('id' => '149','prenom' => 'William','nom' => 'Monahan'),
  array('id' => '150','prenom' => 'Orlando','nom' => 'Bloom'),
  array('id' => '151','prenom' => 'Eva','nom' => 'Green'),
  array('id' => '152','prenom' => 'Jeremy','nom' => 'Irons'),
  array('id' => '153','prenom' => 'David','nom' => 'Thewlis'),
  array('id' => '154','prenom' => 'Stanley','nom' => 'Kubrick'),
  array('id' => '155','prenom' => 'Brian W.','nom' => 'Cook'),
  array('id' => '156','prenom' => 'Diane','nom' => 'Johnson'),
  array('id' => '157','prenom' => 'Jack','nom' => 'Nicholson'),
  array('id' => '158','prenom' => 'Shelley','nom' => 'Duvall'),
  array('id' => '159','prenom' => 'Danny','nom' => 'Lloyd'),
  array('id' => '160','prenom' => 'Denis','nom' => 'Villeneuve'),
  array('id' => '161','prenom' => 'Aaron','nom' => 'Guzikowski'),
  array('id' => '162','prenom' => 'Kira','nom' => 'Davis'),
  array('id' => '163','prenom' => 'Broderick','nom' => 'Johnson'),
  array('id' => '164','prenom' => 'Adam','nom' => 'Kolbrenner'),
  array('id' => '165','prenom' => 'Andrew','nom' => 'Kosove'),
  array('id' => '166','prenom' => 'Mark','nom' => 'Wahlberg'),
  array('id' => '167','prenom' => 'Robyn','nom' => 'Meisinger'),
  array('id' => '168','prenom' => 'Hugh','nom' => 'Jackman'),
  array('id' => '169','prenom' => 'Jake','nom' => 'Gyllenhaal'),
  array('id' => '170','prenom' => 'Viola','nom' => 'Davis'),
  array('id' => '171','prenom' => 'Maria','nom' => 'Bello'),
  array('id' => '172','prenom' => 'Terrence','nom' => 'Howard'),
  array('id' => '173','prenom' => 'Paul','nom' => 'Dano'),
  array('id' => '174','prenom' => 'Matthew','nom' => 'Vaughn'),
  array('id' => '175','prenom' => 'Jane','nom' => 'Goldman'),
  array('id' => '176','prenom' => 'Adam','nom' => 'Bohling'),
  array('id' => '177','prenom' => 'Tarquin','nom' => 'Pack'),
  array('id' => '178','prenom' => 'David','nom' => 'Reid'),
  array('id' => '179','prenom' => 'Kris','nom' => 'Thykier'),
  array('id' => '180','prenom' => 'Aaron Taylor-','nom' => 'Johnson'),
  array('id' => '181','prenom' => 'Chloë Grace','nom' => 'Moretz'),
  array('id' => '182','prenom' => 'Nicolas','nom' => 'Cage'),
  array('id' => '183','prenom' => 'Christopher','nom' => 'Mintz-Plasse'),
  array('id' => '184','prenom' => 'Mark','nom' => 'Strong'),
  array('id' => '185','prenom' => 'James','nom' => 'Cameron'),
  array('id' => '186','prenom' => 'William','nom' => 'Wisher Jr'),
  array('id' => '187','prenom' => 'Arnold','nom' => 'Schwarzenegger'),
  array('id' => '188','prenom' => 'Edward','nom' => 'Furlong'),
  array('id' => '189','prenom' => 'Linda','nom' => 'Hamilton'),
  array('id' => '190','prenom' => 'Robert','nom' => 'Patrick'),
  array('id' => '191','prenom' => 'Joe','nom' => 'Morton'),
  array('id' => '192','prenom' => 'Luc','nom' => 'Besson'),
  array('id' => '193','prenom' => 'Robert Mark','nom' => 'Kamen'),
  array('id' => '194','prenom' => 'Patrice','nom' => 'Ledoux'),
  array('id' => '195','prenom' => 'Bruce','nom' => 'Willis'),
  array('id' => '196','prenom' => 'Milla','nom' => 'Jovovich'),
  array('id' => '197','prenom' => 'Ian','nom' => 'Holm'),
  array('id' => '198','prenom' => 'Chris','nom' => 'Tucker'),
  array('id' => '199','prenom' => 'James','nom' => 'Mangold'),
  array('id' => '200','prenom' => 'Halsted','nom' => 'Welles'),
  array('id' => '201','prenom' => 'Michael','nom' => 'Brandt'),
  array('id' => '202','prenom' => 'Derek','nom' => 'Haas'),
  array('id' => '203','prenom' => 'Cathy','nom' => 'Konrad'),
  array('id' => '204','prenom' => 'Ben','nom' => 'Foster'),
  array('id' => '205','prenom' => 'Logan','nom' => 'Lerman'),
  array('id' => '206','prenom' => 'George','nom' => 'Miller'),
  array('id' => '207','prenom' => 'Brendan','nom' => 'McCarthy'),
  array('id' => '208','prenom' => 'Nick','nom' => 'Lathouris'),
  array('id' => '209','prenom' => 'Doug','nom' => 'Mitchell'),
  array('id' => '210','prenom' => 'P. J.','nom' => 'Voeten'),
  array('id' => '211','prenom' => 'Tom','nom' => 'Hardy'),
  array('id' => '212','prenom' => 'Charlize','nom' => 'Theron'),
  array('id' => '213','prenom' => 'Hugh','nom' => 'Keays-Byrne'),
  array('id' => '214','prenom' => 'Nicholas','nom' => 'Hoult'),
  array('id' => '215','prenom' => 'Scott','nom' => 'Derrickson'),
  array('id' => '216','prenom' => 'C. Robert','nom' => 'Cargill'),
  array('id' => '217','prenom' => 'Jason','nom' => 'Blum'),
  array('id' => '218','prenom' => 'Brian','nom' => 'Kavanaugh-Jones'),
  array('id' => '219','prenom' => 'Ethan','nom' => 'Hawke'),
  array('id' => '220','prenom' => 'Juliet','nom' => 'Rylance')
);

/* `filmo`.`produit` */
$produit = array(
    array('id' => '1','titre' => 'Princesse Mononoké','synopsis' => 'Japon, XVe siècle. Jadis protégée par des animaux géants, la forêt se dépeuple à cause de l\'homme.
  Blessé par un sanglier rendu fou par les démons, le jeune guerrier Ashitaka quitte les siens et part à la recherche du dieu-cerf qui seul pourra défaire le sortilège qui lui gangrène le bras.
  Au cours de son voyage, Ashitaka rencontre Lady Eboshi, à la tête d’une communauté de forgerons, qui doit se défendre contre ceux qui lui reprochent de détruire la forêt pour alimenter ses forges.
  Parmi ses pires ennemis se trouve San, une jeune fille sauvage élevée par des loups, aussi appelée Princesse Mononoké, la princesse des spectres...','date_sortie' => '1997-07-12','duree' => '2h23','image' => 'princesse_mononoke.webp','prix_ttc' => '12.99','prix_four' => '8.99','stock' => '200','actif' => '1'),
    array('id' => '2','titre' => 'Le voyage de Chihiro','synopsis' => 'Chihiro, une fillette de 10 ans, est en route vers sa nouvelle demeure en compagnie de ses parents.
  Au cours du voyage, la famille fait une halte dans un parc à thème qui leur paraît délabré.
  Lors de la visite, les parents s’arrêtent dans un des bâtiments pour déguster quelques mets très appétissants, apparus comme par enchantement.
  Hélas cette nourriture les transforme en porcs.
  Prise de panique, Chihiro s’enfuit et se retrouve seule dans cet univers fantasmagorique ; elle rencontre alors l’énigmatique Haku, son seul allié dans cette terrible épreuve...','date_sortie' => '2001-07-20','duree' => '2h05','image' => 'chihiro.webp','prix_ttc' => '13.99','prix_four' => '9.99','stock' => '300','actif' => '1'),
    array('id' => '3','titre' => 'Le Château ambulant','synopsis' => 'La jeune Sophie, 18 ans, travaille inlassablement dans la chapellerie autrefois tenue par son père, malheureusement décédé.
  Résignée à son sort, c’est lors de l’une de ses rares sorties en ville qu’elle fait la connaissance du beau Hauru, un magicien.
  Mais la sorcière des Landes, jalouse de cette rencontre, jette un sort à Sophie, la transformant en vieille dame.
  Accablée par sa nouvelle apparence, Sophie s’enfuit dans les montagnes et tombe sur la demeure de Hauru : son Château Ambulant.
  Et si tout ceci n’était que le commencement d’une merveilleuse histoire ?','date_sortie' => '2004-11-20','duree' => '1h59','image' => 'le_chateau_ambulant.webp','prix_ttc' => '11.99','prix_four' => '6.99','stock' => '200','actif' => '1'),
    array('id' => '4','titre' => 'Le Tombeau des lucioles','synopsis' => 'Japon, été 1945. Après le bombardement de Kobé, Seita, un adolescent de quatorze ans et sa petite soeur de quatre ans, Setsuko, orphelins, vont s\'installer chez leur tante à quelques dizaines de kilomètres de chez eux.
  Celle-ci leur fait comprendre qu\'ils sont une gêne pour la famille et doivent mériter leur riz quotidien.
  Seita décide de partir avec sa petite soeur. Ils se réfugient dans un bunker désaffecté en pleine campagne et vivent des jours heureux illuminés par la présence de milliers de lucioles.
  Mais bientôt la nourriture commence cruellement à manquer.','date_sortie' => '1988-04-16','duree' => '1h30','image' => 'le_tombeau_des_lucioles.webp','prix_ttc' => '11.99','prix_four' => '6.99','stock' => '200','actif' => '1'),
    array('id' => '5','titre' => 'Seven','synopsis' => 'Pour conclure sa carrière, l\'inspecteur Somerset, vieux flic blasé, tombe à sept jours de la retraite sur un criminel peu ordinaire.
  John Doe, c\'est ainsi que se fait appeler l\'assassin, a décidé de nettoyer la société des maux qui la rongent en commettant sept meurtres basés sur les sept péchés capitaux: la gourmandise, l\'avarice, la paresse, l\'orgueil, la luxure, l\'envie et la colère.','date_sortie' => '1995-07-22','duree' => '2h10','image' => 'seven.webp','prix_ttc' => '9.99','prix_four' => '5.99','stock' => '200','actif' => '1'),
    array('id' => '6','titre' => 'Fight Club','synopsis' => 'Le narrateur, sans identité précise, vit seul, travaille seul, dort seul, mange seul ses plateaux-repas pour une personne comme beaucoup d\'autres personnes seules qui connaissent la misère humaine, morale et sexuelle.
  C\'est pourquoi il va devenir membre du Fight club, un lieu clandestin où il va pouvoir retrouver sa virilité, l\'échange et la communication.
  Ce club est dirigé par Tyler Durden, une sorte d\'anarchiste entre gourou et philosophe qui prêche l\'amour de son prochain.','date_sortie' => '1999-10-15','duree' => '2h19','image' => 'fight_club.webp','prix_ttc' => '9.99','prix_four' => '4.99','stock' => '250','actif' => '1'),
    array('id' => '7','titre' => 'Requiem for a Dream','synopsis' => 'Harry Goldfarb est un junkie. Il passe ses journées en compagnie de sa petite amie Marion et son copain Tyrone.
  Ensemble, ils s\'inventent un paradis artificiel. En quête d\'une vie meilleure, le trio est entraîné dans une spirale infernale qui les enfonce toujours un peu plus dans l\'angoisse et le désespoir.
  La mère d\'Harry, Sara, souffre d\'une autre forme d\'addiction, la télévision. Juive, fantasque et veuve depuis des années, elle vit seule à Coney Island et nourrit dans le secret l\'espoir de participer un jour à son émission préférée.
  Afin de satisfaire aux canons esthétiques de la télévision, elle s\'astreint à un régime draconien. Un jour, elle le sait, elle passera de l\'autre côté de l\'écran.','date_sortie' => '2000-10-27','duree' => '1h42','image' => 'requiem_for_a_dream.webp','prix_ttc' => '14.99','prix_four' => '9.99','stock' => '150','actif' => '1'),
    array('id' => '8','titre' => 'Shutter Island','synopsis' => 'En 1954, le marshal Teddy Daniels et son coéquipier Chuck Aule sont envoyés enquêter sur l\'île de Shutter Island, dans un hôpital psychiatrique où sont internés de dangereux criminels.
  L\'une des patientes, Rachel Solando, a inexplicablement disparu. Comment la meurtrière a-t-elle pu sortir d\'une cellule fermée de l\'extérieur ? Le seul indice retrouvé dans la pièce est une feuille de papier sur laquelle on peut lire une suite de chiffres et de lettres sans signification apparente.
  Oeuvre cohérente d\'une malade, ou cryptogramme ?','date_sortie' => '2010-02-19','duree' => '2h17','image' => 'shutter_island.webp','prix_ttc' => '9.99','prix_four' => '4.99','stock' => '250','actif' => '1'),
    array('id' => '9','titre' => 'Taxi Driver','synopsis' => 'Vétéran de la Guerre du Vietnam, Travis Bickle est chauffeur de taxi dans la ville de New York.
  Ses rencontres nocturnes et la violence quotidienne dont il est témoin lui font peu à peu perdre la tête.
  Il se charge bientôt de délivrer une prostituée mineure de ses souteneurs.','date_sortie' => '1976-02-08','duree' => '1h55','image' => 'taxi_driver.webp','prix_ttc' => '7.99','prix_four' => '4.99','stock' => '250','actif' => '1'),
    array('id' => '10','titre' => 'Akira','synopsis' => 'En juillet 1988, une mystérieuse explosion détruit Tokyo, déclenchant la troisième guerre mondiale.
  31 ans plus tard, en 2019, Néo Tokyo, la mégalopole construite sur la baie de Tokyo a retrouvé sa prospérité d’antan et se prépare à l’évènement majeur des Jeux olympiques de 2020.
  Dans l\'ombre, les choses sont moins réjouissantes, le chômage augmente et les actions des dissidents se multiplient, les citadins cherchent leur salut dans les cultes religieux et les drogues.
  Les plus jeunes se réunissent en gang rebelles et se défient dans d’interminables courses de motos à travers la mégalopole.
  Au cours d’une de leurs échappées, Kaneda et Tetsuo manquent d’écraser un enfant. Un enfant étrange, au visage de vieillard, appelé n ° 26.
  Kaneda et ses amis sont arrêtés par la police alors que n ° 26 et Tetsuo, blessé, sont emmenés par l\'armée.
  Tetsuo est prisonnier d’un laboratoire et devient l’objet de tests ultrasecrets qui le dotent de pouvoirs surnaturels.
  C’est là qu’il apprend qui est AKIRA, ce garçon a la force incroyable à l’origine de la destruction de Tokyo, il y a 31 ans.','date_sortie' => '1988-07-16','duree' => '2h04','image' => 'akira.webp','prix_ttc' => '13.99','prix_four' => '8.99','stock' => '250','actif' => '1'),
    array('id' => '11','titre' => 'Interstellar','synopsis' => 'Le film raconte les aventures d’un groupe d’explorateurs qui utilisent une faille récemment découverte dans l’espace-temps afin de repousser les limites humaines et partir à la conquête des distances astronomiques dans un voyage interstellaire.','date_sortie' => '2014-10-26','duree' => '2h49','image' => 'interstellar.webp','prix_ttc' => '9.99','prix_four' => '5.99','stock' => '200','actif' => '1'),
    array('id' => '12','titre' => 'The Dark Knight','synopsis' => 'Dans ce nouveau volet, Batman augmente les mises dans sa guerre contre le crime.
  Avec l\'appui du lieutenant de police Jim Gordon et du procureur de Gotham, Harvey Dent, Batman vise à éradiquer le crime organisé qui pullule dans la ville.
  Leur association est très efficace mais elle sera bientôt bouleversée par le chaos déclenché par un criminel que les citoyens de Gotham connaissent sous le nom de Joker.','date_sortie' => '2008-07-18','duree' => '2h32','image' => 'the_dark_knight.webp','prix_ttc' => '13.99','prix_four' => '6.99','stock' => '300','actif' => '1'),
    array('id' => '13','titre' => 'Shrek','synopsis' => 'Shrek, un ogre verdâtre, cynique et malicieux, a élu domicile dans un marécage qu\'il croit être un havre de paix.
  Un matin, alors qu\'il sort faire sa toilette, il découvre de petites créatures agaçantes qui errent dans son marais.
  Shrek se rend alors au château du seigneur Lord Farquaad, qui aurait soit-disant expulsé ces êtres de son royaume.
  Ce dernier souhaite épouser la princesse Fiona, mais celle-ci est retenue prisonnière par un abominable dragon.
  Il lui faut un chevalier assez brave pour secourir la belle. Shrek accepte d\'accomplir cette mission.
  En échange, le seigneur devra débarrasser son marécage de ces créatures envahissantes.
  Or, la princesse Fiona cache un secret terrifiant qui va entraîner Shrek et son compagnon l\'âne dans une palpitante et périlleuse aventure.','date_sortie' => '2004-04-22','duree' => '1h29','image' => 'shrek.webp','prix_ttc' => '6.99','prix_four' => '3.99','stock' => '300','actif' => '1'),
    array('id' => '14','titre' => 'Inglourious Basterds','synopsis' => 'Dans la France occupée de 1940, Shosanna Dreyfus assiste à l\'exécution de sa famille tombée entre les mains du colonel nazi Hans Landa.
  Shosanna s\'échappe de justesse et s\'enfuit à Paris où elle se construit une nouvelle identité en devenant exploitante d\'une salle de cinéma.
  Quelque part ailleurs en Europe, le lieutenant Aldo Raine forme un groupe de soldats juifs américains pour mener des actions punitives particulièrement sanglantes contre les nazis.
  Les bâtards, nom sous lequel leurs ennemis vont apprendre à les connaître, se joignent à l\'actrice allemande et agent secret Bridget von Hammersmark pour tenter d\'éliminer les hauts dignitaires du Troisième Reich.
  Leurs destins vont se jouer à l\'entrée du cinéma où Shosanna est décidée à mettre à exécution une vengeance très personnelle...','date_sortie' => '2009-08-19','duree' => '2h39','image' => 'inglourious_basterds.webp','prix_ttc' => '8.99','prix_four' => '3.99','stock' => '200','actif' => '1'),
    array('id' => '15','titre' => 'Django Unchained','synopsis' => 'Dans le sud des États-Unis, deux ans avant la guerre de Sécession, le Dr King Schultz, un chasseur de primes allemand, fait l’acquisition de Django, un esclave qui peut l’aider à traquer les frères Brittle, les meurtriers qu’il recherche.
  Schultz promet à Django de lui rendre sa liberté lorsqu’il aura capturé les Brittle – morts ou vifs.
  Alors que les deux hommes pistent les dangereux criminels, Django n’oublie pas que son seul but est de retrouver Broomhilda, sa femme, dont il fut séparé à cause du commerce des esclaves…
  Lorsque Django et Schultz arrivent dans l’immense plantation du puissant Calvin Candie, ils éveillent les soupçons de Stephen, un esclave qui sert Candie et a toute sa confiance.
  Le moindre de leurs mouvements est désormais épié par une dangereuse organisation de plus en plus proche…
  Si Django et Schultz veulent espérer s’enfuir avec Broomhilda, ils vont devoir choisir entre l’indépendance et la solidarité, entre le sacrifice et la survie…','date_sortie' => '2012-12-25','duree' => '2h44','image' => 'django_unchained.webp','prix_ttc' => '7.99','prix_four' => '3.99','stock' => '250','actif' => '1'),
    array('id' => '16','titre' => 'Once Upon a Time… in Hollywood','synopsis' => 'En 1969, la star de télévision Rick Dalton et le cascadeur Cliff Booth, sa doublure de longue date, poursuivent leurs carrières au sein d’une industrie qu’ils ne reconnaissent plus.','date_sortie' => '2019-07-26','duree' => '2h41','image' => 'one_upton_a_time_in_hollywood.webp','prix_ttc' => '7.99','prix_four' => '3.99','stock' => '150','actif' => '1'),
    array('id' => '17','titre' => 'Collatéral','synopsis' => 'Max est taxi de nuit à Los Angeles.
  Un soir, il se lie d\'amitié avec une dénommée Annie Farrell, une belle femme procureur montée à l\'arrière de son véhicule.
  Quelques minutes plus tard, c\'est au tour d\'un homme prénommé Vincent de monter dans le taxi. Un businessman, selon toute apparence, avec un emploi du temps chargé : pas moins de cinq rendez-vous à tenir dans la nuit.
  Max accepte de lui louer ses services jusqu\'au petit matin, en échange de 600 dollars.
  Premier arrêt. Vincent entre dans un immeuble. Un coup de feu éclate aussitôt, un corps plonge dans le vide, s\'écrasant sur le toit du taxi.
  Vincent redescend et, sous la menace de son arme, oblige Max à dissimuler le cadavre dans le coffre et à reprendre son mortel périple.
  Un chauffeur de taxi, un tueur implacable, cinq cibles à éliminer, des agents des stups et une équipe du FBI... Leurs destins se joueront cette nuit...','date_sortie' => '2004-08-06','duree' => '2h00','image' => 'collateral.webp','prix_ttc' => '5.99','prix_four' => '1.99','stock' => '300','actif' => '1'),
    array('id' => '18','titre' => 'Public Enemies','synopsis' => 'Basé sur l\'histoire vraie de John Dillinger, un braqueur de banque hors pair qui a sévi à de nombreuses reprises dans l\'Amérique des années 30.
  Avancé comme l\'ennemi public numéro 1 par le patron du FBI, John Edgar Hoover, Dillinger sera traqué sans relâche par Melvin Purvis, l\'un des agents fédéraux des plus efficaces.','date_sortie' => '2009-07-01','duree' => '2h20','image' => 'public_enemies.webp','prix_ttc' => '7.99','prix_four' => '3.99','stock' => '200','actif' => '1'),
    array('id' => '19','titre' => 'Signes','synopsis' => 'A Bucks County, en Pennsylvanie.
  Après la perte de sa femme, Graham Hess a rendu sa charge de pasteur.
  Tout en s\'occupant de sa ferme, il tente d\'élever de son mieux ses deux enfants, Morgan et Bo.
  Son jeune frère Merrill, une ancienne gloire du base-ball, est revenu vivre avec lui pour l\'aider.
  Un matin, la petite famille découvre l\'apparition dans ses champs de gigantesques signes et cercles étranges.
  Des extra-terrestres seraient-ils à l\'origine de tels phénomènes surnaturels ?
  Graham et Merrill vont s\'efforcer de percer le mystère qui entoure ces dessins.','date_sortie' => '2002-08-02','duree' => '1h45','image' => 'signes.webp','prix_ttc' => '7.99','prix_four' => '3.99','stock' => '150','actif' => '1'),
    array('id' => '20','titre' => 'Sixième Sens','synopsis' => 'Cole Sear, garçonnet de huit ans, est hanté par un terrible secret.
  Son imaginaire est visité par des esprits menaçants.
  Trop jeune pour comprendre le pourquoi de ces apparitions et traumatisé par ces pouvoirs paranormaux, Cole s\'enferme dans une peur maladive et ne veut révéler à personne la cause de son enfermement, à l\'exception d\'un psychologue pour enfants.
  La recherche d\'une explication rationnelle guidera l\'enfant et le thérapeute vers une vérité foudroyante et inexplicable.','date_sortie' => '1999-08-02','duree' => '1h47','image' => 'sixieme_sens.webp','prix_ttc' => '6.99','prix_four' => '1.99','stock' => '150','actif' => '1'),
    array('id' => '21','titre' => 'Gladiator','synopsis' => 'Le général romain Maximus est le plus fidèle soutien de l\'empereur Marc Aurèle, qu\'il a conduit de victoire en victoire avec une bravoure et un dévouement exemplaires.
  Jaloux du prestige de Maximus, et plus encore de l\'amour que lui voue l\'empereur, le fils de MarcAurèle, Commode, s\'arroge brutalement le pouvoir, puis ordonne l\'arrestation du général et son exécution.
  Maximus échappe à ses assassins mais ne peut empêcher le massacre de sa famille. Capturé par un marchand d\'esclaves, il devient gladiateur et prépare sa vengeance.','date_sortie' => '2000-05-01','duree' => '2h35','image' => 'gladiator.webp','prix_ttc' => '9.99','prix_four' => '4.99','stock' => '200','actif' => '1'),
    array('id' => '22','titre' => 'Kingdom of Heaven','synopsis' => 'L\'aventure extraordinaire d\'un homme ordinaire, précipité dans un conflit qui va durer des décennies : les croisades.
  Etranger sur une terre qui lui est étrangère, il va servir un roi condamné, s\'éprendre d\'une troublante et inaccessible reine avant d\'être fait chevalier.
  Il lui faudra protéger les habitants de Jérusalem, dont une immense armée a entrepris le siège, sans jamais cesser de lutter pour maintenir une paix fragile...','date_sortie' => '2005-05-06','duree' => '2h25','image' => 'kingdom_of_heaven.webp','prix_ttc' => '10.99','prix_four' => '4.99','stock' => '250','actif' => '1'),
    array('id' => '23','titre' => 'Shining','synopsis' => 'Écrivain, Jack Torrance est engagé comme gardien, pendant tout l’hiver, d’un grand hôtel isolé du Colorado – l’Overlook – où il espère surmonter enfin sa panne d’inspiration.
  Il s’y installe avec sa femme Wendy et son fils Danny, doté d’un don de médium.
  Tandis que Jack n’avance pas dans son livre et que son fils est de plus en plus hanté par des visions terrifiantes, il découvre les terribles secrets de l’hôtel et bascule peu à peu dans une forme de folie meurtrière où il s’en prend à sa propre famille…','date_sortie' => '1980-05-23','duree' => '2h23','image' => 'shining.webp','prix_ttc' => '8.99','prix_four' => '3.99','stock' => '100','actif' => '1'),
    array('id' => '24','titre' => 'Prisoners','synopsis' => 'Dans la banlieue de Boston, deux fillettes de 6 ans, Anna et Joy, ont disparu.
  Le détective Loki privilégie la thèse du kidnapping suite au témoignage de Keller, le père d’Anna.
  Le suspect numéro 1 est rapidement arrêté mais est relâché quelques jours plus tard faute de preuve, entraînant la fureur de Keller.
  Aveuglé par sa douleur, le père dévasté se lance alors dans une course contre la montre pour retrouver les enfants disparus.
  De son côté, Loki essaie de trouver des indices pour arrêter le coupable avant que Keller ne commette l’irréparable…
  Les jours passent et les chances de retrouver les fillettes s’amenuisent…','date_sortie' => '2013-09-20','duree' => '2h33','image' => 'prisoners.webp','prix_ttc' => '7.99','prix_four' => '3.99','stock' => '200','actif' => '1'),
    array('id' => '25','titre' => 'Kick-Ass','synopsis' => 'Dave Lizewski est un adolescent gavé de comics qui ne vit que pour ce monde de super-héros et d\'incroyables aventures.
  Décidé à vivre son obsession jusque dans la réalité, il se choisit un nom – Kick-Ass – se fabrique lui-même un costume, et se lance dans une bataille effrénée contre le crime.
  Dans son délire, il n\'a qu\'un seul problème : Kick-Ass n\'a pas le moindre superpouvoir... Le voilà pourchassé par toutes les brutes de la ville.
  Mais Kick-Ass s\'associe bientôt à d\'autres délirants copycats décidés eux aussi à faire régner la justice.
  Parmi eux, une enfant de 11 ans, Hit Girl et son père Big Daddy, mais aussi Red Mist.
  Le parrain de la mafia locale, Frank D\'Amico, va leur donner l\'occasion de montrer ce dont ils sont capables...','date_sortie' => '2010-03-26','duree' => '1h57','image' => 'kick_ass.webp','prix_ttc' => '10.99','prix_four' => '3.99','stock' => '300','actif' => '1'),
    array('id' => '26','titre' => 'Terminator 2 : Le Jugement dernier','synopsis' => 'En 1997, les survivants de l\'apocalypse nucléaire poursuivent une guerre sans merci contre les robots et machines qu\'ils ont eux-même créés.
  Pour en finir avec John Connor qui dirige la résistance des hommes, deux cyborgs sont envoyés dans le passé.
  Leur mission : abattre Connor enfant. Le premier modèle de la série Terminator a échoué en 1984.
  Le second, modèle plus performant en liquide métamorphosable, se lance à la poursuite de l\'enfant et de sa mère, Sarah, dans les années quatre-vingt-dix.
  De leur côté, les hommes du futur ont envoyé dans le passé un Terminator chargé de protéger le jeune Connor.
  Le duel des robots va prendre alors des allures titanesques. Et, tandis que l\'enfant enseignera à ce Terminator des rudiments d\'humanité, sa mère tentera par tous les moyens d\'empêcher la création des premières machines intelligentes.
  Avec l\'aide du Terminator qu\'ils ont éduqué, ils combattront pour influencer le futur...','date_sortie' => '1991-07-03','duree' => '2h17','image' => 'terminator_2.webp','prix_ttc' => '9.99','prix_four' => '2.99','stock' => '300','actif' => '1'),
    array('id' => '27','titre' => 'Le Cinquième Élément','synopsis' => 'Au XXIII siècle, dans un univers étrange et coloré, où tout espoir de survie est impossible sans la découverte du cinquième élément, un héros affronte le mal pour sauver l\'humanité.','date_sortie' => '1997-05-07','duree' => '2h06','image' => 'cinquieme_element.webp','prix_ttc' => '9.99','prix_four' => '3.99','stock' => '200','actif' => '1'),
    array('id' => '28','titre' => '3h10 pour Yuma','synopsis' => 'Revenu blessé de la guerre de Sécession, Dan Evans a établi sa famille dans un ranch.
  La sécheresse a ravagé ses terres, décimé son troupeau et miné la considération que lui portent sa femme et ses enfants, en particulier son aîné Will, âgé de 14 ans.
  A la suite d\'une attaque de diligence, le célèbre bandit Ben Wade passe par la ville de Bisbee où il est arrêté avec le concours fortuit de Evans.
  Recherché pour ses hold-up et ses meurtres répétés, Wade doit être convoyé vers Contention, à trois jours de cheval, pour embarquer sur un train à destination de Yuma, où se trouve le tribunal fédéral.
  Contre une prime qui peut sauver son ranch, Dan Evans s\'engage dans l\'escorte qui doit accompagner le dangereux criminel.
  Il est bientôt rejoint par son fils Will, fasciné par l\'aura du tueur.
  Tandis que son gang organise son évasion, Wade engage sur le chemin de Contention un bras de fer psychologique avec ses gardiens, usant à la fois de la peur qu\'il leur inspire et de la séduction qu\'il exerce sur eux...','date_sortie' => '2007-09-07','duree' => '2h02','image' => '3h10_pour_yuma.webp','prix_ttc' => '12.99','prix_four' => '4.99','stock' => '200','actif' => '1'),
    array('id' => '29','titre' => 'Mad Max: Fury Road','synopsis' => 'Hanté par un lourd passé, Mad Max estime que le meilleur moyen de survivre est de rester seul.
  Cependant, il se retrouve embarqué par une bande qui parcourt la Désolation à bord d\'un véhicule militaire piloté par l\'Imperator Furiosa.
  Ils fuient la Citadelle où sévit le terrible Immortan Joe qui s\'est fait voler un objet irremplaçable.
  Enragé, ce Seigneur de guerre envoie ses hommes pour traquer les rebelles impitoyablement…','date_sortie' => '2015-05-15','duree' => '2h00','image' => 'madmax_fury_road.webp','prix_ttc' => '9.99','prix_four' => '2.99','stock' => '250','actif' => '1'),
    array('id' => '30','titre' => 'Sinister','synopsis' => 'Ellison est un auteur de romans policiers inspirés de faits réels.
  Dans l’espoir d’écrire un nouveau livre à succès, il emménage avec sa famille dans une maison où les anciens propriétaires ont été retrouvés inexplicablement pendus.
  Ellison y découvre dans le grenier des bobines 8mm contenant les images de meurtres d’autres familles.
  Qui a filmé ces tueries et pour quelle raison ?
  Ellison va tenter de répondre à ces questions tandis que le tueur présumé, une entité surnaturelle présente sur les films, menace de plus en plus sa famille.','date_sortie' => '2012-10-05','duree' => '1h50','image' => 'sinister.webp','prix_ttc' => '7.99','prix_four' => '1.99','stock' => '150','actif' => '1')
  );

  /* `filmo`.`genre` */
$genre = array(
    array('id' => '1','nom' => 'Action'),
    array('id' => '2','nom' => 'Comédie'),
    array('id' => '3','nom' => 'Drame'),
    array('id' => '4','nom' => 'Science-Fiction'),
    array('id' => '5','nom' => 'Thriller'),
    array('id' => '6','nom' => 'Aventure'),
    array('id' => '7','nom' => 'Animation'),
    array('id' => '8','nom' => 'Fantastique'),
    array('id' => '9','nom' => 'Guerre'),
    array('id' => '10','nom' => 'Policier'),
    array('id' => '11','nom' => 'Western'),
    array('id' => '12','nom' => 'Biopic'),
    array('id' => '13','nom' => 'Historique'),
    array('id' => '14','nom' => 'Epouvante-horreur')
  );
  
  /* `filmo`.`role` */
$role = array(
    array('id' => '1','nom' => 'Acteur'),
    array('id' => '2','nom' => 'Réalisateur'),
    array('id' => '3','nom' => 'Scénariste'),
    array('id' => '4','nom' => 'Producteur'),
    array('id' => '5','nom' => 'Voix originales')
  );

/* `filmo`.`fournisseur` */
$fournisseur = array(
  array('id' => '1','nom' => 'MovieSupplier1','adresse' => '123 Main St, City','telephone' => '0234567890','email' => 'supplier@test.com'),
  array('id' => '2','nom' => 'MovieSupplier2','adresse' => '456 Oak St, Town','telephone' => '0876543210','email' => 'supplier@test.com')
);

  /* `filmo`.`utilisateur` */
$utilisateur = array(
  array('id' => '1','email' => 'john@test.com','password' => 'test','nom' => 'Smith','prenom' => 'John','telephone' => '0612345678','role' => '0','coefficient' => '1.20','responsable_id' => '13'),
  array('id' => '2','email' => 'jane@test.com','password' => 'test','nom' => 'Johnson','prenom' => 'Jane','telephone' => '0623456789','role' => '0','coefficient' => '1.20','responsable_id' => '13'),
  array('id' => '3','email' => 'bob@test.com','password' => 'test','nom' => 'Doe','prenom' => 'Bob','telephone' => '0634567890','role' => '0','coefficient' => '1.20','responsable_id' => '13'),
  array('id' => '4','email' => 'alice@test.com','password' => 'test','nom' => 'Miller','prenom' => 'Alice','telephone' => '0645678901','role' => '0','coefficient' => '1.20','responsable_id' => '13'),
  array('id' => '5','email' => 'sophie@test.com','password' => 'test','nom' => 'Lefèvre','prenom' => 'Sophie','telephone' => '0601122334','role' => '0','coefficient' => '1.20','responsable_id' => '13'),
  array('id' => '6','email' => 'adam@test.com','password' => 'test','nom' => 'Moreau','prenom' => 'Adam','telephone' => '0678765432','role' => '0','coefficient' => '1.20','responsable_id' => '13'),
  array('id' => '7','email' => 'clara@test.com','password' => 'test','nom' => 'Dubois','prenom' => 'Clara','telephone' => '0654345678','role' => '0','coefficient' => '1.20','responsable_id' => '13'),
  array('id' => '8','email' => 'mohamed@test.com','password' => 'test','nom' => 'Bouvier','prenom' => 'Mohamed','telephone' => '0687654321','role' => '0','coefficient' => '1.20','responsable_id' => '13'),
  array('id' => '9','email' => 'zoé@test.com','password' => 'test','nom' => 'Bonnet','prenom' => 'Zoé','telephone' => '0654321098','role' => '0','coefficient' => '1.20','responsable_id' => '13'),
  array('id' => '10','email' => 'lucie@test.com','password' => 'test','nom' => 'Leroux','prenom' => 'Lucie','telephone' => '0679911234','role' => '1','coefficient' => '2.20','responsable_id' => '14'),
  array('id' => '11','email' => 'nathan@test.com','password' => 'test','nom' => 'Roux','prenom' => 'Nathan','telephone' => '0615365678','role' => '1','coefficient' => '3.20','responsable_id' => '14'),
  array('id' => '12','email' => 'léa@test.com','password' => 'test','nom' => 'Fournier','prenom' => 'Léa','telephone' => '0690123456','role' => '1','coefficient' => '2.50','responsable_id' => '14'),
  array('id' => '13','email' => 'commercial_harris@test.com','password' => 'test','nom' => 'Harris','prenom' => 'William','telephone' => '0612345879','role' => '2','coefficient' => NULL,'responsable_id' => NULL),
  array('id' => '14','email' => 'commercial_girard@test.com','password' => 'test','nom' => 'Girard','prenom' => 'Hugo','telephone' => '0678901234','role' => '3','coefficient' => NULL,'responsable_id' => NULL),
  array('id' => '15','email' => 'gerant_jean@test.com','password' => 'test','nom' => 'Garnier','prenom' => 'Jean','telephone' => '0609876543','role' => '4','coefficient' => NULL,'responsable_id' => NULL)
);

/* `filmo`.`adresse` */
$adresse = array(
  array('id' => '1','livraison' => '123 Shipping St, City','facturation' => '456 Billing St, City','id_uti' => '1'),
  array('id' => '2','livraison' => '789 Delivery St, Town','facturation' => '101 Invoicing St, Town','id_uti' => '2'),
  array('id' => '3','livraison' => '42 Starlight Lane, Celestia City','facturation' => '42 Starlight Lane, Celestia City','id_uti' => '3'),
  array('id' => '4','livraison' => '101 Galaxy View, Nebula Town','facturation' => '456 Comet Boulevard, Nebula Town','id_uti' => '4'),
  array('id' => '5','livraison' => '12 Enchanted Avenue, Fairytale City','facturation' => '345 Magic Street, Fairytale City','id_uti' => '5'),
  array('id' => '6','livraison' => '1 Sunshine Road, Sunnyville','facturation' => '1 Sunshine Road, Sunnyville','id_uti' => '6'),
  array('id' => '7','livraison' => '22 Riverbank Drive, Riverside','facturation' => '22 Riverbank Drive, Riverside','id_uti' => '7'),
  array('id' => '8','livraison' => '5 Mountain Top, Peaksville','facturation' => '5 Mountain Top, Peaksville','id_uti' => '8'),
  array('id' => '9','livraison' => '8 Meadow Lane, Meadowville','facturation' => '8 Meadow Lane, Meadowville','id_uti' => '9'),
  array('id' => '10','livraison' => '456 Business Park, Commercial City','facturation' => '789 Corporate Avenue, Commercial City','id_uti' => '10'),
  array('id' => '11','livraison' => '101 Industrial Zone, Industrial Town','facturation' => '222 Factory Street, Industrial Town','id_uti' => '11'),
  array('id' => '12','livraison' => '25 Office Plaza, Officeville','facturation' => '333 Executive Street, Officeville','id_uti' => '12')
);

/* `filmo`.`commande` */
$commande = array(
  array('id' => '1','date_commande' => '2022-03-01 12:00:00','total' => '25.98','etat' => '3','id_uti' => '1'),
  array('id' => '2','date_commande' => '2022-04-02 15:30:00','total' => '27.98','etat' => '2','id_uti' => '2'),
  array('id' => '3','date_commande' => '2022-05-03 18:45:00','total' => '66.95','etat' => '3','id_uti' => '1'),
  array('id' => '4','date_commande' => '2022-06-01 14:00:00','total' => '23.98','etat' => '1','id_uti' => '4'),
  array('id' => '5','date_commande' => '2022-07-02 16:45:00','total' => '23.98','etat' => '2','id_uti' => '5'),
  array('id' => '6','date_commande' => '2023-01-10 08:15:00','total' => '32.97','etat' => '3','id_uti' => '7'),
  array('id' => '7','date_commande' => '2023-02-15 17:30:00','total' => '24.97','etat' => '0','id_uti' => '9'),
  array('id' => '8','date_commande' => '2023-03-20 13:45:00','total' => '59.90','etat' => '2','id_uti' => '11'),
  array('id' => '9','date_commande' => '2023-04-25 09:30:00','total' => '24.98','etat' => '1','id_uti' => '3'),
  array('id' => '10','date_commande' => '2023-05-30 14:45:00','total' => '33.96','etat' => '3','id_uti' => '6'),
  array('id' => '11','date_commande' => '2023-07-05 11:00:00','total' => '7.99','etat' => '4','id_uti' => '8'),
  array('id' => '12','date_commande' => '2023-08-10 16:15:00','total' => '269.70','etat' => '2','id_uti' => '10'),
  array('id' => '13','date_commande' => '2023-09-15 12:30:00','total' => '17.98','etat' => '1','id_uti' => '4'),
  array('id' => '14','date_commande' => '2023-10-20 14:45:00','total' => '199.80','etat' => '3','id_uti' => '12'),
  array('id' => '15','date_commande' => '2023-11-25 10:00:00','total' => '20.98','etat' => '2','id_uti' => '5'),
  array('id' => '16','date_commande' => '2023-12-25 18:15:00','total' => '47.96','etat' => '1','id_uti' => '1'),
  array('id' => '17','date_commande' => '2024-01-05 14:30:00','total' => '30.97','etat' => '3','id_uti' => '9'),
  array('id' => '18','date_commande' => '2024-02-10 09:45:00','total' => '33.96','etat' => '2','id_uti' => '2'),
  array('id' => '19','date_commande' => '2024-03-15 16:00:00','total' => '20.98','etat' => '1','id_uti' => '4'),
  array('id' => '20','date_commande' => '2024-04-20 12:15:00','total' => '23.97','etat' => '3','id_uti' => '6')
);

/* `filmo`.`details_commande` */
$details_commande = array(
  array('id_pro' => '1','id_co' => '1','quantite' => '2'),
  array('id_pro' => '1','id_co' => '3','quantite' => '3'),
  array('id_pro' => '1','id_co' => '16','quantite' => '1'),
  array('id_pro' => '2','id_co' => '2','quantite' => '2'),
  array('id_pro' => '2','id_co' => '3','quantite' => '2'),
  array('id_pro' => '3','id_co' => '4','quantite' => '2'),
  array('id_pro' => '3','id_co' => '5','quantite' => '1'),
  array('id_pro' => '3','id_co' => '16','quantite' => '1'),
  array('id_pro' => '4','id_co' => '5','quantite' => '1'),
  array('id_pro' => '4','id_co' => '6','quantite' => '1'),
  array('id_pro' => '5','id_co' => '18','quantite' => '1'),
  array('id_pro' => '6','id_co' => '9','quantite' => '1'),
  array('id_pro' => '7','id_co' => '9','quantite' => '1'),
  array('id_pro' => '8','id_co' => '12','quantite' => '15'),
  array('id_pro' => '8','id_co' => '18','quantite' => '1'),
  array('id_pro' => '9','id_co' => '12','quantite' => '15'),
  array('id_pro' => '9','id_co' => '18','quantite' => '1'),
  array('id_pro' => '10','id_co' => '6','quantite' => '1'),
  array('id_pro' => '11','id_co' => '16','quantite' => '1'),
  array('id_pro' => '12','id_co' => '16','quantite' => '1'),
  array('id_pro' => '13','id_co' => '6','quantite' => '1'),
  array('id_pro' => '13','id_co' => '13','quantite' => '1'),
  array('id_pro' => '14','id_co' => '7','quantite' => '1'),
  array('id_pro' => '15','id_co' => '7','quantite' => '1'),
  array('id_pro' => '15','id_co' => '15','quantite' => '1'),
  array('id_pro' => '15','id_co' => '20','quantite' => '1'),
  array('id_pro' => '16','id_co' => '7','quantite' => '1'),
  array('id_pro' => '17','id_co' => '8','quantite' => '10'),
  array('id_pro' => '17','id_co' => '18','quantite' => '1'),
  array('id_pro' => '19','id_co' => '20','quantite' => '1'),
  array('id_pro' => '20','id_co' => '11','quantite' => '1'),
  array('id_pro' => '21','id_co' => '19','quantite' => '1'),
  array('id_pro' => '22','id_co' => '17','quantite' => '1'),
  array('id_pro' => '22','id_co' => '19','quantite' => '1'),
  array('id_pro' => '23','id_co' => '10','quantite' => '2'),
  array('id_pro' => '24','id_co' => '20','quantite' => '1'),
  array('id_pro' => '25','id_co' => '13','quantite' => '1'),
  array('id_pro' => '26','id_co' => '14','quantite' => '20'),
  array('id_pro' => '27','id_co' => '17','quantite' => '1'),
  array('id_pro' => '28','id_co' => '15','quantite' => '1'),
  array('id_pro' => '29','id_co' => '17','quantite' => '1'),
  array('id_pro' => '30','id_co' => '10','quantite' => '2')
);

/* `filmo`.`facture` */
$facture = array(
  array('id' => '1','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2022-03-01','date_paiement' => '2022-03-01','payer' => '1','date_limite' => NULL,'id_co' => '1'),
  array('id' => '2','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2022-04-02','date_paiement' => '2022-04-02','payer' => '1','date_limite' => NULL,'id_co' => '2'),
  array('id' => '3','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2022-05-03','date_paiement' => '2022-05-03','payer' => '1','date_limite' => NULL,'id_co' => '3'),
  array('id' => '4','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2022-06-01','date_paiement' => '2022-06-01','payer' => '1','date_limite' => NULL,'id_co' => '4'),
  array('id' => '5','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2022-07-02','date_paiement' => '2022-07-02','payer' => '1','date_limite' => NULL,'id_co' => '5'),
  array('id' => '6','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2023-01-10','date_paiement' => '2023-01-10','payer' => '1','date_limite' => NULL,'id_co' => '6'),
  array('id' => '7','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2023-02-15','date_paiement' => '2023-02-15','payer' => '1','date_limite' => NULL,'id_co' => '7'),
  array('id' => '8','mode_de_paiement' => 'Cheque','date_facture' => '2023-03-25','date_paiement' => NULL,'payer' => '0','date_limite' => '2023-04-30','id_co' => '8'),
  array('id' => '9','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2023-04-25','date_paiement' => '2023-04-25','payer' => '1','date_limite' => NULL,'id_co' => '9'),
  array('id' => '10','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2023-05-30','date_paiement' => '2023-05-30','payer' => '1','date_limite' => NULL,'id_co' => '10'),
  array('id' => '11','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2023-07-05','date_paiement' => '2023-07-05','payer' => '1','date_limite' => NULL,'id_co' => '11'),
  array('id' => '12','mode_de_paiement' => 'Cheque','date_facture' => '2023-08-20','date_paiement' => NULL,'payer' => '0','date_limite' => '2023-09-30','id_co' => '12'),
  array('id' => '13','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2023-09-15','date_paiement' => '2023-09-15','payer' => '1','date_limite' => NULL,'id_co' => '13'),
  array('id' => '14','mode_de_paiement' => 'Cheque','date_facture' => '2023-11-01','date_paiement' => '2023-11-30','payer' => '1','date_limite' => '2023-12-30','id_co' => '14'),
  array('id' => '15','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2023-11-25','date_paiement' => '2023-11-25','payer' => '1','date_limite' => NULL,'id_co' => '15'),
  array('id' => '16','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2023-12-25','date_paiement' => '2023-12-25','payer' => '1','date_limite' => NULL,'id_co' => '16'),
  array('id' => '17','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2024-01-05','date_paiement' => '2024-01-05','payer' => '1','date_limite' => NULL,'id_co' => '17'),
  array('id' => '18','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2024-02-10','date_paiement' => '2024-02-10','payer' => '1','date_limite' => NULL,'id_co' => '18'),
  array('id' => '19','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2024-03-15','date_paiement' => '2024-03-15','payer' => '1','date_limite' => NULL,'id_co' => '19'),
  array('id' => '20','mode_de_paiement' => 'Carte Bancaire','date_facture' => '2024-04-20','date_paiement' => '2024-04-20','payer' => '1','date_limite' => NULL,'id_co' => '20')
);

/* `filmo`.`livraison` */
$livraison = array(
  array('id' => '1','date_livraison' => '2022-03-04','id_co' => '1'),
  array('id' => '2','date_livraison' => '2022-04-05','id_co' => '2'),
  array('id' => '3','date_livraison' => '2022-05-06','id_co' => '3'),
  array('id' => '4','date_livraison' => '2022-06-04','id_co' => '4'),
  array('id' => '5','date_livraison' => '2022-06-05','id_co' => '5'),
  array('id' => '6','date_livraison' => '2023-01-13','id_co' => '6'),
  array('id' => '7','date_livraison' => '2023-02-18','id_co' => '7'),
  array('id' => '8','date_livraison' => '2023-03-25','id_co' => '8'),
  array('id' => '9','date_livraison' => '2023-04-28','id_co' => '9'),
  array('id' => '10','date_livraison' => '2023-06-03','id_co' => '10'),
  array('id' => '11','date_livraison' => '2023-07-08','id_co' => '11'),
  array('id' => '12','date_livraison' => '2023-08-20','id_co' => '12'),
  array('id' => '13','date_livraison' => '2023-09-18','id_co' => '13'),
  array('id' => '14','date_livraison' => '2023-10-25','id_co' => '14'),
  array('id' => '15','date_livraison' => '2023-11-28','id_co' => '15'),
  array('id' => '16','date_livraison' => '2023-12-28','id_co' => '16'),
  array('id' => '17','date_livraison' => '2024-01-08','id_co' => '17'),
  array('id' => '18','date_livraison' => '2024-02-13','id_co' => '18'),
  array('id' => '19','date_livraison' => '2024-03-18','id_co' => '19'),
  array('id' => '20','date_livraison' => '2024-04-23','id_co' => '20')
);

  /* `filmo`.`r_film_perso` */
$r_film_perso = array(
    array('id_pro' => '1','id_per' => '1'),
    array('id_pro' => '1','id_per' => '2'),
    array('id_pro' => '1','id_per' => '3'),
    array('id_pro' => '1','id_per' => '4'),
    array('id_pro' => '1','id_per' => '5'),
    array('id_pro' => '1','id_per' => '6'),
    array('id_pro' => '1','id_per' => '7'),
    array('id_pro' => '1','id_per' => '8'),
    array('id_pro' => '1','id_per' => '9'),
    array('id_pro' => '1','id_per' => '10'),
    array('id_pro' => '1','id_per' => '11'),
    array('id_pro' => '1','id_per' => '12'),
    array('id_pro' => '2','id_per' => '1'),
    array('id_pro' => '2','id_per' => '2'),
    array('id_pro' => '2','id_per' => '13'),
    array('id_pro' => '2','id_per' => '14'),
    array('id_pro' => '2','id_per' => '15'),
    array('id_pro' => '2','id_per' => '16'),
    array('id_pro' => '2','id_per' => '17'),
    array('id_pro' => '2','id_per' => '18'),
    array('id_pro' => '2','id_per' => '19'),
    array('id_pro' => '2','id_per' => '20'),
    array('id_pro' => '3','id_per' => '1'),
    array('id_pro' => '3','id_per' => '2'),
    array('id_pro' => '3','id_per' => '5'),
    array('id_pro' => '3','id_per' => '20'),
    array('id_pro' => '3','id_per' => '21'),
    array('id_pro' => '3','id_per' => '22'),
    array('id_pro' => '3','id_per' => '23'),
    array('id_pro' => '3','id_per' => '24'),
    array('id_pro' => '3','id_per' => '25'),
    array('id_pro' => '3','id_per' => '26'),
    array('id_pro' => '3','id_per' => '27'),
    array('id_pro' => '4','id_per' => '28'),
    array('id_pro' => '4','id_per' => '29'),
    array('id_pro' => '4','id_per' => '30'),
    array('id_pro' => '4','id_per' => '31'),
    array('id_pro' => '4','id_per' => '32'),
    array('id_pro' => '4','id_per' => '33'),
    array('id_pro' => '5','id_per' => '34'),
    array('id_pro' => '5','id_per' => '35'),
    array('id_pro' => '5','id_per' => '36'),
    array('id_pro' => '5','id_per' => '37'),
    array('id_pro' => '5','id_per' => '38'),
    array('id_pro' => '5','id_per' => '39'),
    array('id_pro' => '5','id_per' => '40'),
    array('id_pro' => '6','id_per' => '34'),
    array('id_pro' => '6','id_per' => '37'),
    array('id_pro' => '6','id_per' => '41'),
    array('id_pro' => '6','id_per' => '42'),
    array('id_pro' => '6','id_per' => '43'),
    array('id_pro' => '6','id_per' => '44'),
    array('id_pro' => '7','id_per' => '45'),
    array('id_pro' => '7','id_per' => '46'),
    array('id_pro' => '7','id_per' => '47'),
    array('id_pro' => '7','id_per' => '48'),
    array('id_pro' => '7','id_per' => '49'),
    array('id_pro' => '7','id_per' => '50'),
    array('id_pro' => '7','id_per' => '51'),
    array('id_pro' => '8','id_per' => '52'),
    array('id_pro' => '8','id_per' => '53'),
    array('id_pro' => '8','id_per' => '54'),
    array('id_pro' => '8','id_per' => '55'),
    array('id_pro' => '8','id_per' => '56'),
    array('id_pro' => '8','id_per' => '57'),
    array('id_pro' => '9','id_per' => '52'),
    array('id_pro' => '9','id_per' => '58'),
    array('id_pro' => '9','id_per' => '59'),
    array('id_pro' => '9','id_per' => '60'),
    array('id_pro' => '9','id_per' => '61'),
    array('id_pro' => '9','id_per' => '62'),
    array('id_pro' => '9','id_per' => '63'),
    array('id_pro' => '9','id_per' => '64'),
    array('id_pro' => '10','id_per' => '65'),
    array('id_pro' => '10','id_per' => '66'),
    array('id_pro' => '10','id_per' => '67'),
    array('id_pro' => '10','id_per' => '68'),
    array('id_pro' => '10','id_per' => '69'),
    array('id_pro' => '10','id_per' => '70'),
    array('id_pro' => '10','id_per' => '71'),
    array('id_pro' => '11','id_per' => '72'),
    array('id_pro' => '11','id_per' => '73'),
    array('id_pro' => '11','id_per' => '74'),
    array('id_pro' => '11','id_per' => '75'),
    array('id_pro' => '11','id_per' => '76'),
    array('id_pro' => '11','id_per' => '77'),
    array('id_pro' => '11','id_per' => '78'),
    array('id_pro' => '11','id_per' => '79'),
    array('id_pro' => '11','id_per' => '81'),
    array('id_pro' => '12','id_per' => '72'),
    array('id_pro' => '12','id_per' => '73'),
    array('id_pro' => '12','id_per' => '75'),
    array('id_pro' => '12','id_per' => '78'),
    array('id_pro' => '12','id_per' => '82'),
    array('id_pro' => '12','id_per' => '83'),
    array('id_pro' => '12','id_per' => '84'),
    array('id_pro' => '12','id_per' => '85'),
    array('id_pro' => '12','id_per' => '86'),
    array('id_pro' => '12','id_per' => '87'),
    array('id_pro' => '12','id_per' => '88'),
    array('id_pro' => '12','id_per' => '89'),
    array('id_pro' => '13','id_per' => '90'),
    array('id_pro' => '13','id_per' => '91'),
    array('id_pro' => '13','id_per' => '92'),
    array('id_pro' => '13','id_per' => '93'),
    array('id_pro' => '13','id_per' => '94'),
    array('id_pro' => '13','id_per' => '95'),
    array('id_pro' => '13','id_per' => '96'),
    array('id_pro' => '13','id_per' => '97'),
    array('id_pro' => '14','id_per' => '37'),
    array('id_pro' => '14','id_per' => '98'),
    array('id_pro' => '14','id_per' => '99'),
    array('id_pro' => '14','id_per' => '100'),
    array('id_pro' => '14','id_per' => '101'),
    array('id_pro' => '14','id_per' => '102'),
    array('id_pro' => '14','id_per' => '103'),
    array('id_pro' => '14','id_per' => '104'),
    array('id_pro' => '15','id_per' => '55'),
    array('id_pro' => '15','id_per' => '98'),
    array('id_pro' => '15','id_per' => '101'),
    array('id_pro' => '15','id_per' => '105'),
    array('id_pro' => '15','id_per' => '106'),
    array('id_pro' => '15','id_per' => '107'),
    array('id_pro' => '15','id_per' => '108'),
    array('id_pro' => '16','id_per' => '37'),
    array('id_pro' => '16','id_per' => '55'),
    array('id_pro' => '16','id_per' => '98'),
    array('id_pro' => '16','id_per' => '109'),
    array('id_pro' => '16','id_per' => '110'),
    array('id_pro' => '16','id_per' => '111'),
    array('id_pro' => '16','id_per' => '112'),
    array('id_pro' => '16','id_per' => '113'),
    array('id_pro' => '17','id_per' => '56'),
    array('id_pro' => '17','id_per' => '106'),
    array('id_pro' => '17','id_per' => '114'),
    array('id_pro' => '17','id_per' => '115'),
    array('id_pro' => '17','id_per' => '116'),
    array('id_pro' => '17','id_per' => '117'),
    array('id_pro' => '17','id_per' => '118'),
    array('id_pro' => '18','id_per' => '83'),
    array('id_pro' => '18','id_per' => '114'),
    array('id_pro' => '18','id_per' => '119'),
    array('id_pro' => '18','id_per' => '120'),
    array('id_pro' => '18','id_per' => '121'),
    array('id_pro' => '18','id_per' => '122'),
    array('id_pro' => '18','id_per' => '123'),
    array('id_pro' => '19','id_per' => '124'),
    array('id_pro' => '19','id_per' => '125'),
    array('id_pro' => '19','id_per' => '126'),
    array('id_pro' => '19','id_per' => '127'),
    array('id_pro' => '19','id_per' => '128'),
    array('id_pro' => '19','id_per' => '129'),
    array('id_pro' => '19','id_per' => '130'),
    array('id_pro' => '19','id_per' => '131'),
    array('id_pro' => '20','id_per' => '124'),
    array('id_pro' => '20','id_per' => '125'),
    array('id_pro' => '20','id_per' => '132'),
    array('id_pro' => '20','id_per' => '133'),
    array('id_pro' => '20','id_per' => '134'),
    array('id_pro' => '20','id_per' => '135'),
    array('id_pro' => '20','id_per' => '136'),
    array('id_pro' => '20','id_per' => '137'),
    array('id_pro' => '21','id_per' => '128'),
    array('id_pro' => '21','id_per' => '138'),
    array('id_pro' => '21','id_per' => '139'),
    array('id_pro' => '21','id_per' => '140'),
    array('id_pro' => '21','id_per' => '141'),
    array('id_pro' => '21','id_per' => '142'),
    array('id_pro' => '21','id_per' => '143'),
    array('id_pro' => '21','id_per' => '144'),
    array('id_pro' => '21','id_per' => '145'),
    array('id_pro' => '21','id_per' => '146'),
    array('id_pro' => '21','id_per' => '147'),
    array('id_pro' => '21','id_per' => '148'),
    array('id_pro' => '22','id_per' => '138'),
    array('id_pro' => '22','id_per' => '149'),
    array('id_pro' => '22','id_per' => '150'),
    array('id_pro' => '22','id_per' => '151'),
    array('id_pro' => '22','id_per' => '152'),
    array('id_pro' => '22','id_per' => '153'),
    array('id_pro' => '23','id_per' => '154'),
    array('id_pro' => '23','id_per' => '155'),
    array('id_pro' => '23','id_per' => '156'),
    array('id_pro' => '23','id_per' => '157'),
    array('id_pro' => '23','id_per' => '158'),
    array('id_pro' => '23','id_per' => '159'),
    array('id_pro' => '24','id_per' => '160'),
    array('id_pro' => '24','id_per' => '161'),
    array('id_pro' => '24','id_per' => '162'),
    array('id_pro' => '24','id_per' => '163'),
    array('id_pro' => '24','id_per' => '164'),
    array('id_pro' => '24','id_per' => '165'),
    array('id_pro' => '24','id_per' => '166'),
    array('id_pro' => '24','id_per' => '167'),
    array('id_pro' => '24','id_per' => '168'),
    array('id_pro' => '24','id_per' => '169'),
    array('id_pro' => '24','id_per' => '170'),
    array('id_pro' => '24','id_per' => '171'),
    array('id_pro' => '24','id_per' => '172'),
    array('id_pro' => '24','id_per' => '173'),
    array('id_pro' => '25','id_per' => '37'),
    array('id_pro' => '25','id_per' => '174'),
    array('id_pro' => '25','id_per' => '175'),
    array('id_pro' => '25','id_per' => '176'),
    array('id_pro' => '25','id_per' => '177'),
    array('id_pro' => '25','id_per' => '178'),
    array('id_pro' => '25','id_per' => '179'),
    array('id_pro' => '25','id_per' => '180'),
    array('id_pro' => '25','id_per' => '181'),
    array('id_pro' => '25','id_per' => '182'),
    array('id_pro' => '25','id_per' => '183'),
    array('id_pro' => '25','id_per' => '184'),
    array('id_pro' => '26','id_per' => '185'),
    array('id_pro' => '26','id_per' => '186'),
    array('id_pro' => '26','id_per' => '187'),
    array('id_pro' => '26','id_per' => '188'),
    array('id_pro' => '26','id_per' => '189'),
    array('id_pro' => '26','id_per' => '190'),
    array('id_pro' => '26','id_per' => '191'),
    array('id_pro' => '27','id_per' => '86'),
    array('id_pro' => '27','id_per' => '192'),
    array('id_pro' => '27','id_per' => '193'),
    array('id_pro' => '27','id_per' => '194'),
    array('id_pro' => '27','id_per' => '195'),
    array('id_pro' => '27','id_per' => '196'),
    array('id_pro' => '27','id_per' => '197'),
    array('id_pro' => '27','id_per' => '198'),
    array('id_pro' => '28','id_per' => '83'),
    array('id_pro' => '28','id_per' => '144'),
    array('id_pro' => '28','id_per' => '199'),
    array('id_pro' => '28','id_per' => '200'),
    array('id_pro' => '28','id_per' => '201'),
    array('id_pro' => '28','id_per' => '202'),
    array('id_pro' => '28','id_per' => '203'),
    array('id_pro' => '28','id_per' => '204'),
    array('id_pro' => '28','id_per' => '205'),
    array('id_pro' => '29','id_per' => '206'),
    array('id_pro' => '29','id_per' => '207'),
    array('id_pro' => '29','id_per' => '208'),
    array('id_pro' => '29','id_per' => '209'),
    array('id_pro' => '29','id_per' => '210'),
    array('id_pro' => '29','id_per' => '211'),
    array('id_pro' => '29','id_per' => '212'),
    array('id_pro' => '29','id_per' => '213'),
    array('id_pro' => '29','id_per' => '214'),
    array('id_pro' => '30','id_per' => '215'),
    array('id_pro' => '30','id_per' => '216'),
    array('id_pro' => '30','id_per' => '217'),
    array('id_pro' => '30','id_per' => '218'),
    array('id_pro' => '30','id_per' => '219'),
    array('id_pro' => '30','id_per' => '220')
  );

  /* `filmo`.`r_genre_film` */
$r_genre_film = array(
    array('id_pro' => '1','id_gen' => '3'),
    array('id_pro' => '1','id_gen' => '6'),
    array('id_pro' => '1','id_gen' => '7'),
    array('id_pro' => '1','id_gen' => '8'),
    array('id_pro' => '2','id_gen' => '6'),
    array('id_pro' => '2','id_gen' => '7'),
    array('id_pro' => '2','id_gen' => '8'),
    array('id_pro' => '3','id_gen' => '6'),
    array('id_pro' => '3','id_gen' => '7'),
    array('id_pro' => '3','id_gen' => '8'),
    array('id_pro' => '4','id_gen' => '3'),
    array('id_pro' => '4','id_gen' => '7'),
    array('id_pro' => '4','id_gen' => '9'),
    array('id_pro' => '5','id_gen' => '3'),
    array('id_pro' => '5','id_gen' => '5'),
    array('id_pro' => '5','id_gen' => '10'),
    array('id_pro' => '6','id_gen' => '3'),
    array('id_pro' => '6','id_gen' => '5'),
    array('id_pro' => '7','id_gen' => '3'),
    array('id_pro' => '8','id_gen' => '3'),
    array('id_pro' => '8','id_gen' => '5'),
    array('id_pro' => '9','id_gen' => '3'),
    array('id_pro' => '10','id_gen' => '1'),
    array('id_pro' => '10','id_gen' => '3'),
    array('id_pro' => '10','id_gen' => '4'),
    array('id_pro' => '10','id_gen' => '7'),
    array('id_pro' => '11','id_gen' => '3'),
    array('id_pro' => '11','id_gen' => '4'),
    array('id_pro' => '12','id_gen' => '1'),
    array('id_pro' => '12','id_gen' => '5'),
    array('id_pro' => '13','id_gen' => '2'),
    array('id_pro' => '13','id_gen' => '6'),
    array('id_pro' => '13','id_gen' => '7'),
    array('id_pro' => '13','id_gen' => '8'),
    array('id_pro' => '14','id_gen' => '9'),
    array('id_pro' => '15','id_gen' => '11'),
    array('id_pro' => '16','id_gen' => '2'),
    array('id_pro' => '16','id_gen' => '3'),
    array('id_pro' => '17','id_gen' => '3'),
    array('id_pro' => '17','id_gen' => '5'),
    array('id_pro' => '17','id_gen' => '10'),
    array('id_pro' => '18','id_gen' => '3'),
    array('id_pro' => '18','id_gen' => '10'),
    array('id_pro' => '18','id_gen' => '12'),
    array('id_pro' => '19','id_gen' => '3'),
    array('id_pro' => '19','id_gen' => '4'),
    array('id_pro' => '19','id_gen' => '8'),
    array('id_pro' => '20','id_gen' => '3'),
    array('id_pro' => '20','id_gen' => '5'),
    array('id_pro' => '21','id_gen' => '1'),
    array('id_pro' => '21','id_gen' => '6'),
    array('id_pro' => '21','id_gen' => '13'),
    array('id_pro' => '22','id_gen' => '1'),
    array('id_pro' => '22','id_gen' => '13'),
    array('id_pro' => '23','id_gen' => '5'),
    array('id_pro' => '23','id_gen' => '14'),
    array('id_pro' => '24','id_gen' => '5'),
    array('id_pro' => '25','id_gen' => '1'),
    array('id_pro' => '25','id_gen' => '3'),
    array('id_pro' => '26','id_gen' => '1'),
    array('id_pro' => '26','id_gen' => '4'),
    array('id_pro' => '27','id_gen' => '1'),
    array('id_pro' => '27','id_gen' => '4'),
    array('id_pro' => '28','id_gen' => '3'),
    array('id_pro' => '28','id_gen' => '11'),
    array('id_pro' => '29','id_gen' => '1'),
    array('id_pro' => '29','id_gen' => '4'),
    array('id_pro' => '30','id_gen' => '5'),
    array('id_pro' => '30','id_gen' => '14')
  );

  /* `filmo`.`r_role_perso` */
$r_role_perso = array(
    array('id_pro' => '1','id_per' => '1','id_ro' => '2'),
    array('id_pro' => '1','id_per' => '1','id_ro' => '3'),
    array('id_pro' => '1','id_per' => '2','id_ro' => '4'),
    array('id_pro' => '1','id_per' => '3','id_ro' => '5'),
    array('id_pro' => '1','id_per' => '4','id_ro' => '5'),
    array('id_pro' => '1','id_per' => '5','id_ro' => '5'),
    array('id_pro' => '1','id_per' => '6','id_ro' => '5'),
    array('id_pro' => '1','id_per' => '7','id_ro' => '5'),
    array('id_pro' => '1','id_per' => '8','id_ro' => '5'),
    array('id_pro' => '1','id_per' => '9','id_ro' => '5'),
    array('id_pro' => '1','id_per' => '10','id_ro' => '5'),
    array('id_pro' => '1','id_per' => '11','id_ro' => '5'),
    array('id_pro' => '1','id_per' => '12','id_ro' => '5'),
    array('id_pro' => '2','id_per' => '1','id_ro' => '2'),
    array('id_pro' => '2','id_per' => '1','id_ro' => '3'),
    array('id_pro' => '2','id_per' => '2','id_ro' => '4'),
    array('id_pro' => '2','id_per' => '13','id_ro' => '5'),
    array('id_pro' => '2','id_per' => '14','id_ro' => '5'),
    array('id_pro' => '2','id_per' => '15','id_ro' => '5'),
    array('id_pro' => '2','id_per' => '16','id_ro' => '5'),
    array('id_pro' => '2','id_per' => '17','id_ro' => '5'),
    array('id_pro' => '2','id_per' => '18','id_ro' => '5'),
    array('id_pro' => '2','id_per' => '19','id_ro' => '5'),
    array('id_pro' => '2','id_per' => '20','id_ro' => '5'),
    array('id_pro' => '3','id_per' => '1','id_ro' => '2'),
    array('id_pro' => '3','id_per' => '1','id_ro' => '3'),
    array('id_pro' => '3','id_per' => '1','id_ro' => '4'),
    array('id_pro' => '3','id_per' => '2','id_ro' => '4'),
    array('id_pro' => '3','id_per' => '5','id_ro' => '5'),
    array('id_pro' => '3','id_per' => '20','id_ro' => '5'),
    array('id_pro' => '3','id_per' => '21','id_ro' => '5'),
    array('id_pro' => '3','id_per' => '22','id_ro' => '5'),
    array('id_pro' => '3','id_per' => '23','id_ro' => '5'),
    array('id_pro' => '3','id_per' => '24','id_ro' => '5'),
    array('id_pro' => '3','id_per' => '25','id_ro' => '5'),
    array('id_pro' => '3','id_per' => '26','id_ro' => '5'),
    array('id_pro' => '3','id_per' => '27','id_ro' => '5'),
    array('id_pro' => '4','id_per' => '28','id_ro' => '2'),
    array('id_pro' => '4','id_per' => '28','id_ro' => '3'),
    array('id_pro' => '4','id_per' => '29','id_ro' => '4'),
    array('id_pro' => '4','id_per' => '30','id_ro' => '5'),
    array('id_pro' => '4','id_per' => '31','id_ro' => '5'),
    array('id_pro' => '4','id_per' => '32','id_ro' => '5'),
    array('id_pro' => '4','id_per' => '33','id_ro' => '5'),
    array('id_pro' => '5','id_per' => '34','id_ro' => '2'),
    array('id_pro' => '5','id_per' => '35','id_ro' => '3'),
    array('id_pro' => '5','id_per' => '36','id_ro' => '4'),
    array('id_pro' => '5','id_per' => '37','id_ro' => '1'),
    array('id_pro' => '5','id_per' => '38','id_ro' => '1'),
    array('id_pro' => '5','id_per' => '39','id_ro' => '1'),
    array('id_pro' => '5','id_per' => '40','id_ro' => '1'),
    array('id_pro' => '6','id_per' => '34','id_ro' => '2'),
    array('id_pro' => '6','id_per' => '37','id_ro' => '1'),
    array('id_pro' => '6','id_per' => '41','id_ro' => '3'),
    array('id_pro' => '6','id_per' => '42','id_ro' => '4'),
    array('id_pro' => '6','id_per' => '43','id_ro' => '1'),
    array('id_pro' => '6','id_per' => '44','id_ro' => '1'),
    array('id_pro' => '7','id_per' => '45','id_ro' => '2'),
    array('id_pro' => '7','id_per' => '45','id_ro' => '3'),
    array('id_pro' => '7','id_per' => '46','id_ro' => '3'),
    array('id_pro' => '7','id_per' => '47','id_ro' => '4'),
    array('id_pro' => '7','id_per' => '48','id_ro' => '1'),
    array('id_pro' => '7','id_per' => '49','id_ro' => '1'),
    array('id_pro' => '7','id_per' => '50','id_ro' => '1'),
    array('id_pro' => '7','id_per' => '51','id_ro' => '1'),
    array('id_pro' => '8','id_per' => '52','id_ro' => '2'),
    array('id_pro' => '8','id_per' => '52','id_ro' => '4'),
    array('id_pro' => '8','id_per' => '53','id_ro' => '3'),
    array('id_pro' => '8','id_per' => '54','id_ro' => '4'),
    array('id_pro' => '8','id_per' => '55','id_ro' => '1'),
    array('id_pro' => '8','id_per' => '56','id_ro' => '1'),
    array('id_pro' => '8','id_per' => '57','id_ro' => '1'),
    array('id_pro' => '9','id_per' => '52','id_ro' => '2'),
    array('id_pro' => '9','id_per' => '58','id_ro' => '3'),
    array('id_pro' => '9','id_per' => '59','id_ro' => '4'),
    array('id_pro' => '9','id_per' => '60','id_ro' => '4'),
    array('id_pro' => '9','id_per' => '61','id_ro' => '1'),
    array('id_pro' => '9','id_per' => '62','id_ro' => '1'),
    array('id_pro' => '9','id_per' => '63','id_ro' => '1'),
    array('id_pro' => '9','id_per' => '64','id_ro' => '1'),
    array('id_pro' => '10','id_per' => '65','id_ro' => '2'),
    array('id_pro' => '10','id_per' => '65','id_ro' => '3'),
    array('id_pro' => '10','id_per' => '66','id_ro' => '3'),
    array('id_pro' => '10','id_per' => '67','id_ro' => '4'),
    array('id_pro' => '10','id_per' => '68','id_ro' => '5'),
    array('id_pro' => '10','id_per' => '69','id_ro' => '5'),
    array('id_pro' => '10','id_per' => '70','id_ro' => '5'),
    array('id_pro' => '10','id_per' => '71','id_ro' => '5'),
    array('id_pro' => '11','id_per' => '72','id_ro' => '2'),
    array('id_pro' => '11','id_per' => '72','id_ro' => '3'),
    array('id_pro' => '11','id_per' => '72','id_ro' => '4'),
    array('id_pro' => '11','id_per' => '73','id_ro' => '3'),
    array('id_pro' => '11','id_per' => '74','id_ro' => '4'),
    array('id_pro' => '11','id_per' => '75','id_ro' => '4'),
    array('id_pro' => '11','id_per' => '76','id_ro' => '1'),
    array('id_pro' => '11','id_per' => '77','id_ro' => '1'),
    array('id_pro' => '11','id_per' => '78','id_ro' => '1'),
    array('id_pro' => '11','id_per' => '79','id_ro' => '1'),
    array('id_pro' => '11','id_per' => '80','id_ro' => '1'),
    array('id_pro' => '11','id_per' => '81','id_ro' => '1'),
    array('id_pro' => '12','id_per' => '72','id_ro' => '2'),
    array('id_pro' => '12','id_per' => '72','id_ro' => '3'),
    array('id_pro' => '12','id_per' => '72','id_ro' => '4'),
    array('id_pro' => '12','id_per' => '73','id_ro' => '3'),
    array('id_pro' => '12','id_per' => '75','id_ro' => '4'),
    array('id_pro' => '12','id_per' => '78','id_ro' => '1'),
    array('id_pro' => '12','id_per' => '82','id_ro' => '4'),
    array('id_pro' => '12','id_per' => '83','id_ro' => '1'),
    array('id_pro' => '12','id_per' => '84','id_ro' => '1'),
    array('id_pro' => '12','id_per' => '85','id_ro' => '1'),
    array('id_pro' => '12','id_per' => '86','id_ro' => '1'),
    array('id_pro' => '12','id_per' => '87','id_ro' => '1'),
    array('id_pro' => '12','id_per' => '88','id_ro' => '1'),
    array('id_pro' => '12','id_per' => '89','id_ro' => '1'),
    array('id_pro' => '13','id_per' => '90','id_ro' => '2'),
    array('id_pro' => '13','id_per' => '91','id_ro' => '2'),
    array('id_pro' => '13','id_per' => '92','id_ro' => '3'),
    array('id_pro' => '13','id_per' => '93','id_ro' => '4'),
    array('id_pro' => '13','id_per' => '94','id_ro' => '5'),
    array('id_pro' => '13','id_per' => '95','id_ro' => '5'),
    array('id_pro' => '13','id_per' => '96','id_ro' => '5'),
    array('id_pro' => '13','id_per' => '97','id_ro' => '5'),
    array('id_pro' => '14','id_per' => '37','id_ro' => '1'),
    array('id_pro' => '14','id_per' => '98','id_ro' => '2'),
    array('id_pro' => '14','id_per' => '98','id_ro' => '3'),
    array('id_pro' => '14','id_per' => '99','id_ro' => '4'),
    array('id_pro' => '14','id_per' => '100','id_ro' => '1'),
    array('id_pro' => '14','id_per' => '101','id_ro' => '1'),
    array('id_pro' => '14','id_per' => '102','id_ro' => '1'),
    array('id_pro' => '14','id_per' => '103','id_ro' => '1'),
    array('id_pro' => '14','id_per' => '104','id_ro' => '1'),
    array('id_pro' => '15','id_per' => '55','id_ro' => '1'),
    array('id_pro' => '15','id_per' => '98','id_ro' => '2'),
    array('id_pro' => '15','id_per' => '98','id_ro' => '3'),
    array('id_pro' => '15','id_per' => '101','id_ro' => '1'),
    array('id_pro' => '15','id_per' => '105','id_ro' => '4'),
    array('id_pro' => '15','id_per' => '106','id_ro' => '1'),
    array('id_pro' => '15','id_per' => '107','id_ro' => '1'),
    array('id_pro' => '15','id_per' => '108','id_ro' => '1'),
    array('id_pro' => '16','id_per' => '37','id_ro' => '1'),
    array('id_pro' => '16','id_per' => '55','id_ro' => '1'),
    array('id_pro' => '16','id_per' => '98','id_ro' => '2'),
    array('id_pro' => '16','id_per' => '98','id_ro' => '3'),
    array('id_pro' => '16','id_per' => '98','id_ro' => '4'),
    array('id_pro' => '16','id_per' => '109','id_ro' => '4'),
    array('id_pro' => '16','id_per' => '110','id_ro' => '4'),
    array('id_pro' => '16','id_per' => '111','id_ro' => '1'),
    array('id_pro' => '16','id_per' => '112','id_ro' => '1'),
    array('id_pro' => '16','id_per' => '113','id_ro' => '1'),
    array('id_pro' => '17','id_per' => '56','id_ro' => '1'),
    array('id_pro' => '17','id_per' => '106','id_ro' => '1'),
    array('id_pro' => '17','id_per' => '114','id_ro' => '2'),
    array('id_pro' => '17','id_per' => '114','id_ro' => '4'),
    array('id_pro' => '17','id_per' => '115','id_ro' => '3'),
    array('id_pro' => '17','id_per' => '116','id_ro' => '4'),
    array('id_pro' => '17','id_per' => '117','id_ro' => '1'),
    array('id_pro' => '17','id_per' => '118','id_ro' => '1'),
    array('id_pro' => '18','id_per' => '83','id_ro' => '1'),
    array('id_pro' => '18','id_per' => '114','id_ro' => '2'),
    array('id_pro' => '18','id_per' => '114','id_ro' => '3'),
    array('id_pro' => '18','id_per' => '114','id_ro' => '4'),
    array('id_pro' => '18','id_per' => '119','id_ro' => '3'),
    array('id_pro' => '18','id_per' => '120','id_ro' => '3'),
    array('id_pro' => '18','id_per' => '121','id_ro' => '3'),
    array('id_pro' => '18','id_per' => '122','id_ro' => '1'),
    array('id_pro' => '18','id_per' => '123','id_ro' => '1'),
    array('id_pro' => '19','id_per' => '124','id_ro' => '1'),
    array('id_pro' => '19','id_per' => '124','id_ro' => '2'),
    array('id_pro' => '19','id_per' => '124','id_ro' => '3'),
    array('id_pro' => '19','id_per' => '124','id_ro' => '4'),
    array('id_pro' => '19','id_per' => '125','id_ro' => '4'),
    array('id_pro' => '19','id_per' => '126','id_ro' => '4'),
    array('id_pro' => '19','id_per' => '127','id_ro' => '1'),
    array('id_pro' => '19','id_per' => '128','id_ro' => '1'),
    array('id_pro' => '19','id_per' => '129','id_ro' => '1'),
    array('id_pro' => '19','id_per' => '130','id_ro' => '1'),
    array('id_pro' => '19','id_per' => '131','id_ro' => '1'),
    array('id_pro' => '20','id_per' => '124','id_ro' => '1'),
    array('id_pro' => '20','id_per' => '124','id_ro' => '2'),
    array('id_pro' => '20','id_per' => '124','id_ro' => '3'),
    array('id_pro' => '20','id_per' => '125','id_ro' => '4'),
    array('id_pro' => '20','id_per' => '132','id_ro' => '4'),
    array('id_pro' => '20','id_per' => '133','id_ro' => '4'),
    array('id_pro' => '20','id_per' => '134','id_ro' => '1'),
    array('id_pro' => '20','id_per' => '135','id_ro' => '1'),
    array('id_pro' => '20','id_per' => '136','id_ro' => '1'),
    array('id_pro' => '20','id_per' => '137','id_ro' => '1'),
    array('id_pro' => '21','id_per' => '128','id_ro' => '1'),
    array('id_pro' => '21','id_per' => '138','id_ro' => '2'),
    array('id_pro' => '21','id_per' => '139','id_ro' => '3'),
    array('id_pro' => '21','id_per' => '140','id_ro' => '3'),
    array('id_pro' => '21','id_per' => '141','id_ro' => '3'),
    array('id_pro' => '21','id_per' => '142','id_ro' => '4'),
    array('id_pro' => '21','id_per' => '143','id_ro' => '4'),
    array('id_pro' => '21','id_per' => '145','id_ro' => '1'),
    array('id_pro' => '21','id_per' => '146','id_ro' => '1'),
    array('id_pro' => '21','id_per' => '147','id_ro' => '1'),
    array('id_pro' => '21','id_per' => '148','id_ro' => '1'),
    array('id_pro' => '22','id_per' => '138','id_ro' => '2'),
    array('id_pro' => '22','id_per' => '149','id_ro' => '3'),
    array('id_pro' => '22','id_per' => '150','id_ro' => '1'),
    array('id_pro' => '22','id_per' => '151','id_ro' => '1'),
    array('id_pro' => '22','id_per' => '152','id_ro' => '1'),
    array('id_pro' => '22','id_per' => '153','id_ro' => '1'),
    array('id_pro' => '23','id_per' => '154','id_ro' => '2'),
    array('id_pro' => '23','id_per' => '154','id_ro' => '3'),
    array('id_pro' => '23','id_per' => '154','id_ro' => '4'),
    array('id_pro' => '23','id_per' => '155','id_ro' => '2'),
    array('id_pro' => '23','id_per' => '156','id_ro' => '3'),
    array('id_pro' => '23','id_per' => '157','id_ro' => '1'),
    array('id_pro' => '23','id_per' => '158','id_ro' => '1'),
    array('id_pro' => '23','id_per' => '159','id_ro' => '1'),
    array('id_pro' => '24','id_per' => '160','id_ro' => '2'),
    array('id_pro' => '24','id_per' => '161','id_ro' => '3'),
    array('id_pro' => '24','id_per' => '162','id_ro' => '4'),
    array('id_pro' => '24','id_per' => '163','id_ro' => '4'),
    array('id_pro' => '24','id_per' => '164','id_ro' => '4'),
    array('id_pro' => '24','id_per' => '165','id_ro' => '4'),
    array('id_pro' => '24','id_per' => '166','id_ro' => '4'),
    array('id_pro' => '24','id_per' => '167','id_ro' => '4'),
    array('id_pro' => '24','id_per' => '168','id_ro' => '1'),
    array('id_pro' => '24','id_per' => '169','id_ro' => '1'),
    array('id_pro' => '24','id_per' => '170','id_ro' => '1'),
    array('id_pro' => '24','id_per' => '171','id_ro' => '1'),
    array('id_pro' => '24','id_per' => '172','id_ro' => '1'),
    array('id_pro' => '24','id_per' => '173','id_ro' => '1'),
    array('id_pro' => '25','id_per' => '37','id_ro' => '4'),
    array('id_pro' => '25','id_per' => '174','id_ro' => '2'),
    array('id_pro' => '25','id_per' => '174','id_ro' => '3'),
    array('id_pro' => '25','id_per' => '174','id_ro' => '4'),
    array('id_pro' => '25','id_per' => '175','id_ro' => '3'),
    array('id_pro' => '25','id_per' => '176','id_ro' => '4'),
    array('id_pro' => '25','id_per' => '177','id_ro' => '4'),
    array('id_pro' => '25','id_per' => '178','id_ro' => '4'),
    array('id_pro' => '25','id_per' => '179','id_ro' => '4'),
    array('id_pro' => '25','id_per' => '180','id_ro' => '1'),
    array('id_pro' => '25','id_per' => '181','id_ro' => '1'),
    array('id_pro' => '25','id_per' => '182','id_ro' => '1'),
    array('id_pro' => '25','id_per' => '183','id_ro' => '1'),
    array('id_pro' => '25','id_per' => '184','id_ro' => '1'),
    array('id_pro' => '26','id_per' => '185','id_ro' => '2'),
    array('id_pro' => '26','id_per' => '185','id_ro' => '3'),
    array('id_pro' => '26','id_per' => '185','id_ro' => '4'),
    array('id_pro' => '26','id_per' => '186','id_ro' => '3'),
    array('id_pro' => '26','id_per' => '187','id_ro' => '1'),
    array('id_pro' => '26','id_per' => '188','id_ro' => '1'),
    array('id_pro' => '26','id_per' => '189','id_ro' => '1'),
    array('id_pro' => '26','id_per' => '190','id_ro' => '1'),
    array('id_pro' => '26','id_per' => '191','id_ro' => '1'),
    array('id_pro' => '27','id_per' => '86','id_ro' => '1'),
    array('id_pro' => '27','id_per' => '192','id_ro' => '2'),
    array('id_pro' => '27','id_per' => '192','id_ro' => '3'),
    array('id_pro' => '27','id_per' => '193','id_ro' => '3'),
    array('id_pro' => '27','id_per' => '194','id_ro' => '4'),
    array('id_pro' => '27','id_per' => '195','id_ro' => '1'),
    array('id_pro' => '27','id_per' => '196','id_ro' => '1'),
    array('id_pro' => '27','id_per' => '197','id_ro' => '1'),
    array('id_pro' => '27','id_per' => '198','id_ro' => '1'),
    array('id_pro' => '28','id_per' => '83','id_ro' => '1'),
    array('id_pro' => '28','id_per' => '144','id_ro' => '1'),
    array('id_pro' => '28','id_per' => '199','id_ro' => '2'),
    array('id_pro' => '28','id_per' => '200','id_ro' => '3'),
    array('id_pro' => '28','id_per' => '201','id_ro' => '3'),
    array('id_pro' => '28','id_per' => '202','id_ro' => '3'),
    array('id_pro' => '28','id_per' => '203','id_ro' => '4'),
    array('id_pro' => '28','id_per' => '204','id_ro' => '1'),
    array('id_pro' => '28','id_per' => '205','id_ro' => '1'),
    array('id_pro' => '29','id_per' => '206','id_ro' => '2'),
    array('id_pro' => '29','id_per' => '206','id_ro' => '3'),
    array('id_pro' => '29','id_per' => '206','id_ro' => '4'),
    array('id_pro' => '29','id_per' => '207','id_ro' => '3'),
    array('id_pro' => '29','id_per' => '208','id_ro' => '3'),
    array('id_pro' => '29','id_per' => '209','id_ro' => '4'),
    array('id_pro' => '29','id_per' => '210','id_ro' => '4'),
    array('id_pro' => '29','id_per' => '211','id_ro' => '1'),
    array('id_pro' => '29','id_per' => '212','id_ro' => '1'),
    array('id_pro' => '29','id_per' => '213','id_ro' => '1'),
    array('id_pro' => '29','id_per' => '214','id_ro' => '1'),
    array('id_pro' => '30','id_per' => '215','id_ro' => '2'),
    array('id_pro' => '30','id_per' => '215','id_ro' => '3'),
    array('id_pro' => '30','id_per' => '216','id_ro' => '3'),
    array('id_pro' => '30','id_per' => '217','id_ro' => '4'),
    array('id_pro' => '30','id_per' => '218','id_ro' => '4'),
    array('id_pro' => '30','id_per' => '219','id_ro' => '1'),
    array('id_pro' => '30','id_per' => '220','id_ro' => '1')
  );

  /* `filmo`.`r_fourni_film` */
$r_fourni_film = array(
  array('id_pro' => '1','id_four' => '1'),
  array('id_pro' => '2','id_four' => '1'),
  array('id_pro' => '3','id_four' => '2'),
  array('id_pro' => '4','id_four' => '2'),
  array('id_pro' => '5','id_four' => '1'),
  array('id_pro' => '6','id_four' => '1'),
  array('id_pro' => '7','id_four' => '2'),
  array('id_pro' => '8','id_four' => '2'),
  array('id_pro' => '9','id_four' => '1'),
  array('id_pro' => '10','id_four' => '2'),
  array('id_pro' => '11','id_four' => '1'),
  array('id_pro' => '12','id_four' => '1'),
  array('id_pro' => '13','id_four' => '2'),
  array('id_pro' => '14','id_four' => '2'),
  array('id_pro' => '15','id_four' => '1'),
  array('id_pro' => '16','id_four' => '2'),
  array('id_pro' => '17','id_four' => '1'),
  array('id_pro' => '18','id_four' => '2'),
  array('id_pro' => '19','id_four' => '1'),
  array('id_pro' => '20','id_four' => '1'),
  array('id_pro' => '21','id_four' => '2'),
  array('id_pro' => '22','id_four' => '2'),
  array('id_pro' => '23','id_four' => '1'),
  array('id_pro' => '24','id_four' => '2'),
  array('id_pro' => '25','id_four' => '1'),
  array('id_pro' => '26','id_four' => '1'),
  array('id_pro' => '27','id_four' => '2'),
  array('id_pro' => '28','id_four' => '2'),
  array('id_pro' => '29','id_four' => '1'),
  array('id_pro' => '30','id_four' => '2')
);